# Optimization

## Import Libraries

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

import importlib
import numpy as np
import pandas as pd

from src import config
import src.optimization_utils as ou
import src.solutions as s
import src.display as disp
import src.runs as runs
from src.problem import SpineProblem

# Reload to pick up any changes
importlib.reload(ou)
importlib.reload(s)
importlib.reload(disp)
importlib.reload(runs)

pd.set_option('display.max_columns', None)

## Load Models

In [2]:
# Load all models
model_configs = {
    "Mechanical Failure": config.MECH_FAIL_MODEL,
    "L4S1": config.L4S1_MODEL,
    "LL": config.LL_MODEL,
    "T4PA": config.T4PA_MODEL,
    "L1PA": config.L1PA_MODEL,
    "SVA": config.SVA_MODEL,
    "SS": config.SS_MODEL,
    "Global Tilt": config.GLOBAL_TILT_MODEL,
    "ODI": config.ODI_MODEL,
}

bundles = {name: ou.load_model_bundle(path) for name, path in model_configs.items()}

# Verify and display
print("Models loaded and verified:")
for name, bundle in bundles.items():
    status = "✓" if all(k in bundle for k in ["pipe", "features", "target"]) else "✗"
    print(f"  {status} {name}: {bundle.get('model_name', 'N/A')}")

# Extract individual bundles for use
mech_fail_bundle = bundles["Mechanical Failure"]
L4S1_bundle = bundles["L4S1"]
LL_bundle = bundles["LL"]
T4PA_bundle = bundles["T4PA"]
L1PA_bundle = bundles["L1PA"]
SVA_bundle = bundles["SVA"]
SS_bundle = bundles["SS"]
GT_bundle = bundles["Global Tilt"]
ODI_bundle = bundles["ODI"]

# Delta model bundles for postop predictions
delta_bundles = {
    "L4S1": L4S1_bundle,
    "LL": LL_bundle,
    "T4PA": T4PA_bundle,
    "L1PA": L1PA_bundle,
    "SS": SS_bundle,
    "GlobalTilt": GT_bundle,
    "SVA": SVA_bundle,
}

Models loaded and verified:
  ✓ Mechanical Failure: mech_fail_logreg
  ✓ L4S1: Ridge
  ✓ LL: RandomForest
  ✓ T4PA: Ridge
  ✓ L1PA: Ridge
  ✓ SVA: XGBRegressor
  ✓ SS: XGBRegressor
  ✓ Global Tilt: XGBRegressor
  ✓ ODI: Ridge

In [3]:
# ---- Check categories in training data vs each model ----
train_df = pd.read_csv(config.DATA_PROCESSED)
print("Training data:", config.DATA_PROCESSED)
print(f"  Shape: {train_df.shape}")
print(f"  ASA_CLASS unique: {sorted(train_df['ASA_CLASS'].dropna().unique())}")
print(f"  sex unique: {sorted(train_df['sex'].dropna().unique())}")
print(f"  UIV_implant unique: {sorted(train_df['UIV_implant'].dropna().unique())}")
print(f"  num_levels_cat unique: {sorted(train_df['num_levels_cat'].dropna().unique())}")

Training data: /Users/vanjaglisic/Documents/UW_MSDS/CAPSTONE/repo work/Data-Science-Capstone/data/processed/cleaned_for_modeling.csv
  Shape: (271, 109)
  ASA_CLASS unique: ['1', '2', '3', '4', '4E']
  sex unique: ['FEMALE', 'MALE']
  UIV_implant unique: ['FS', 'Hook', 'PS']
  num_levels_cat unique: ['higher', 'lower']

## Optimization Scenarios

Each scenario uses a different set of composite score weights to explore how the optimizer behaves under different objectives. Predefined presets are in `src/runs.py`. To add a new scenario, add a new entry to `runs.PRESETS` and include its key below.

In [4]:
# =============================================================================
# SELECT SCENARIOS TO RUN
# =============================================================================
# Available presets (defined in src/runs.py):
#   "equal"           - All 6 alignment components weighted equally
#   "mech_fail"       - Primarily mech failure, small alignment weights
#   "mech_fail_t4l1pa"- Mech failure + T4PA-L1PA mismatch
#   "l4s1"            - Primarily L4-S1 in ideal range
#   "t4l1pa"          - Primarily T4PA-L1PA mismatch
#   "equal_plus_mech" - Composite (equal) blended 50/50 with mech failure
#   "odi"             - Primarily lowest predicted postop ODI
#   "gap_score"       - Primarily GAP score + category improvement
#   "gap_score_mech_fail" - GAP score + Mechanical Failure
#   "ll"              - Primarily PI-LL mismatch
#
# To add a new scenario: add an entry to runs.PRESETS in src/runs.py,
# then include its key here.

SCENARIOS = ["equal", "mech_fail", "mech_fail_t4l1pa", "l4s1", "t4l1pa", "gap_score", "gap_score_mech_fail", "ll", "odi"]

# Show selected scenarios
for key in SCENARIOS:
    runs.print_preset(runs.PRESETS[key])

============================================================
  Equal Weights (Composite)
  All 6 alignment components and mechanical failure weighted equally
============================================================
                       GAP Score: 0.1429 ◀
                    L1PA penalty: 0.1429 ◀
                    L4S1 penalty: 0.1429 ◀
                  T4L1PA penalty: 0.1429 ◀
                      LL penalty: 0.1429 ◀
        GAP category improvement: 0.1429 ◀
         Mechanical failure prob: 0.1429 ◀

============================================================
  Minimize Mechanical Failure
  Primarily mechanical failure probability, with small alignment weights
============================================================
                       GAP Score: 0.0500 ◀
                    L1PA penalty: 0.0500 ◀
                    L4S1 penalty: 0.0500 ◀
                  T4L1PA penalty: 0.0500 ◀
                      LL penalty: 0.0500 ◀
        GAP category improvement: 0.0500 ◀
         Mechanical failure prob: 0.7000 ◀

============================================================
  Minimize Mechanical Failure + T4L1PA
  Mechanical failure probability and T4PA-L1PA mismatch weighted equally
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.5000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize L4S1 Penalty
  Primarily L4-S1 in ideal range (35-45°), with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.8000 ◀
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize T4L1PA Penalty
  Primarily T4PA-L1PA mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.8000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.5000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.3000 ◀
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score and Mechanical Failure
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.4000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.1000 ◀
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize LL (PI-LL) Penalty
  Primarily PI-LL mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.8000 ◀
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize Postop ODI
  Primarily lowest predicted postoperative ODI, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀
                      ODI postop: 0.8000 ◀

In [5]:
UIV_CHOICES, xl, xu = ou.get_decision_config()

print("UIV_CHOICES:", UIV_CHOICES)
print("xl:", xl)
print("xu:", xu)

# Use column names from config
print(pd.DataFrame([xl, xu], index=["xl","xu"], columns=config.DECISION_VAR_NAMES))

UIV_CHOICES: ['Hook', 'PS', 'FS']
xl: [0 0 0 0 0 0 1 2 0]
xu: [2 1 5 1 1 1 6 4 1]
    uiv_code  num_levels_cat_code  num_interbody_fusion_levels  ALIF  XLIF  \
xl         0                    0                            0     0     0
xu         2                    1                            5     1     1

    TLIF  num_rods  num_pelvic_screws  osteotomy
xl     0         1                  2          0
xu     1         6                  4          1

## Test Patient 1

In [6]:
# Show holdout patients summary
holdout_df = pd.read_csv(config.DATA_HOLDOUT)

summary_cols = [
    'sex', 'age', 'ASA_CLASS',
    "id", "description", "revision", "mech_fail_last",
    "gap_score_preop", "gap_category", "gap_score_postop", "gap_category_postop",
    "UIV_implant", "num_levels_cat", "num_interbody_fusion_levels",
    "ALIF", "XLIF", "TLIF", "num_rods", "num_pelvic_screws", "osteotomy",
    "ODI_preop"
]
display(holdout_df[summary_cols].set_index("id"))

# Select patient
PATIENT_ID = 6380632
patient_fixed = ou.load_patient_data(patient_id=PATIENT_ID, data_path=config.DATA_HOLDOUT)
print(f"\nSelected patient: {PATIENT_ID}")

,sex,age,ASA_CLASS,description,revision,mech_fail_last,gap_score_preop,gap_category,gap_score_postop,gap_category_postop,UIV_implant,num_levels_cat,num_interbody_fusion_levels,ALIF,XLIF,TLIF,num_rods,num_pelvic_screws,osteotomy,ODI_preop
id,,,,,,,,,,,,,,,,,,,,
818588,MALE,78,2.0,mech failure - small GAP improvement;,0,1.0,12.0,SD,10.0,SD,PS,lower,1,0,0,1,3,2,0,NaN
1176294,MALE,71,NaN,mech failure - large GAP improvement;,1,1.0,10.0,SD,1.0,P,FS,lower,1,1,1,0,4,2,1,NaN
2964021,FEMALE,70,3.0,revision - GAP improvement 3 to 1,0,0.0,3.0,MD,1.0,P,PS,lower,2,1,0,0,3,3,0,15.0
6380632,FEMALE,76,3.0,large GAP imporovement,0,0.0,12.0,SD,1.0,P,Hook,higher,2,1,0,0,3,2,0,NaN

Selected patient: 6380632

**Run GA for all scenarios**

For each selected scenario, runs the GA optimizer and collects results. 

**Constraints (all scenarios):** 
- If `num_interbody_fusion_levels > 0`, at least one fusion type (`ALIF`, `XLIF`, or `TLIF`) must be selected.
- If `ALIF=1` and `XLIF=0` and `TLIF=0`, then `num_interbody_fusion_levels` must be < 4.

In [7]:
all_results = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=100,
        n_gen=20,
        seed=42,
        verbose=False,
        top_n=4,
        score_tolerance=2,
    )
    all_results[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 2.52  |  Mech fail: 9.7%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 5.31  |  Mech fail: 7.0%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 4.12  |  Mech fail: 8.2%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 0.66  |  Mech fail: 3.3%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 0.66  |  Mech fail: 3.3%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 5.50  |  Mech fail: 8.2%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 7.20  |  Mech fail: 8.2%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 0.85  |  Mech fail: 3.3%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 1.65  |  Mech fail: 8.2%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [8]:
df_actual = disp.display_actual_outcomes(
    PATIENT_ID, patient_fixed, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: Hook
  num_levels_cat: higher
  num_interbody_fusion_levels: 2
  ALIF: 1
  XLIF: 0
  TLIF: 0
  num_rods: 3
  num_pelvic_screws: 2
  osteotomy (PSO): 0

  Mechanical Failure: No
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 47.6%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   15.50
    [mech_fail]            Minimize Mechanical Failure                 36.34
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        23.78
    [l4s1]                 Minimize L4S1 Penalty                        9.51
    [t4l1pa]               Minimize T4L1PA Penalty                      9.51
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        28.86
    [odi]                  Minimize Postop ODI                          9.51
    [gap_score]            Minimize GAP Score                          33.90
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   39.09
    [ll]                   Minimize LL (PI-LL) Penalty                  9.66

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     30.4           32.5            62.9
1                    SS     33.8           11.5            45.3
2                  L4S1     34.5            7.0            41.5
3            GlobalTilt     42.2          -23.9            18.3
4                  T4PA     24.8          -15.2             9.6
5                  L1PA     12.2           -4.8             7.4
6                    PI     58.6            2.2            60.8
7                    PT     24.8           -9.3            15.5
8                   SVA    154.6         -124.8            29.8
9                   Age       76              -               -
10            GAP Score     12.0              -             1.0
11         GAP Category       SD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   28.2 ⚠          -30.3          -2.1 ⚠
14   L1PA−ideal (|d|≤3)    3.9 ⚠           -4.8          -0.9 ✓
15         L4S1 (35–45)   34.5 ⚠            7.0          41.5 ✓
16    T4PA−L1PA (|d|≤3)   12.6 ⚠          -10.4           2.2 ✓
17     LL−ideal (|d|≤3)  -28.8 ⚠           32.5           3.7 ⚠
18          GAP Cat (P)     SD ⚠              →             P ✓

### Results

In [9]:
from IPython.display import display, Markdown

for key in SCENARIOS:
    r = all_results[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{runs.PRESETS[key]['description']}*"))

    # # Best solution
    # df_comparison = disp.display_optimized_solution(r["best_result"], patient_fixed)
    # display(df_comparison)

    # Top 4 diverse plans
    display(Markdown("**Top diverse plans:**"))
    _ = disp.display_multiple_solutions(r["diverse_df"], patient_fixed)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.3,1.4,1.3,1.3
1,Optimization Score,1.5,2.2,2.5,2.7
2,Mech Fail Prob,2.8%,7.0%,9.2%,10.8%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,2,3
10,ALIF,0,0,0,0
11,XLIF,0,0,1,1
12,TLIF,1,1,0,1
13,num_rods,5,4,6,3
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.7,53.7,53.8
19,SS,44.4,43.8,44.3,44.7
20,L4S1,41.6,42.6,38.1,35.9
21,GlobalTilt,21.5,21.8,21.1,21.6
22,T4PA,5.8,5.8,5.1,7.8
23,L1PA,4.6,3.4,3.9,5.6
24,SVA,87.7,84.1,84.9,86.3
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.8,14.3,13.9
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.9 ✓,4.9 ✓,4.8 ✓
30,L1PA−ideal (|d|≤3),-3.7 ⚠,-4.9 ⚠,-4.4 ⚠,-2.7 ✓
31,L4S1 (35–45),41.6 ✓,42.6 ✓,38.1 ✓,35.9 ✓
32,T4PA−L1PA (|d|≤3),1.2 ✓,2.4 ✓,1.2 ✓,2.2 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.5 ⚠,-5.5 ⚠,-5.4 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.3,1.3,1.3,1.3
1,Optimization Score,2.3,2.7,2.7,3.1
2,Mech Fail Prob,2.8%,3.3%,3.3%,3.9%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,5,3
10,ALIF,0,0,0,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,5,5,4,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.8,53.8,53.8
19,SS,44.4,44.4,44.4,44.4
20,L4S1,41.6,41.5,39.8,41.5
21,GlobalTilt,21.5,21.0,22.1,21.0
22,T4PA,5.8,6.1,6.7,6.3
23,L1PA,4.6,4.5,5.5,4.4
24,SVA,87.7,87.7,88.7,84.1
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.2,14.2,14.2
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.8 ✓,4.8 ✓,4.8 ✓
30,L1PA−ideal (|d|≤3),-3.7 ⚠,-3.8 ⚠,-2.8 ✓,-3.9 ⚠
31,L4S1 (35–45),41.6 ✓,41.5 ✓,39.8 ✓,41.5 ✓
32,T4PA−L1PA (|d|≤3),1.2 ✓,1.6 ✓,1.2 ✓,1.9 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.4 ⚠,-5.4 ⚠,-5.4 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.2,10.2,10.2,10.4
1,Optimization Score,1.2,1.4,2.5,2.6
2,Mech Fail Prob,2.3%,2.8%,5.0%,5.2%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,PS,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,5,5
10,ALIF,0,0,0,1
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,5,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.8,53.7,54.3
19,SS,44.4,44.4,43.8,44.7
20,L4S1,43.4,43.3,44.5,50.7
21,GlobalTilt,21.6,21.0,21.8,21.5
22,T4PA,4.9,5.2,4.7,4.5
23,L1PA,3.6,3.5,2.5,1.8
24,SVA,85.6,85.6,83.0,86.7
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.2,14.8,13.9
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.8 ✓,4.9 ✓,4.3 ✓
30,L1PA−ideal (|d|≤3),-4.7 ⚠,-4.8 ⚠,-5.8 ⚠,-6.5 ⚠
31,L4S1 (35–45),43.4 ✓,43.3 ✓,44.5 ✓,50.7 ⚠
32,T4PA−L1PA (|d|≤3),1.3 ✓,1.7 ✓,2.2 ✓,2.7 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.4 ⚠,-5.5 ⚠,-4.9 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.2,1.4,10.2,10.2
1,Optimization Score,0.5,1.3,1.5,2.1
2,Mech Fail Prob,2.3%,6.6%,7.6%,10.3%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 1 (P),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,PS,FS
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,3,4,5
10,ALIF,0,0,0,0
11,XLIF,0,1,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,5,5
14,num_pelvic_screws,2,2,3,3
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.8,53.7,53.8
19,SS,44.4,44.3,43.9,44.0
20,L4S1,43.4,41.3,45.4,43.1
21,GlobalTilt,21.6,21.1,21.4,21.9
22,T4PA,4.9,5.1,4.3,5.4
23,L1PA,3.6,2.7,1.9,3.2
24,SVA,85.6,84.3,83.5,93.2
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.3,14.7,14.6
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.8 ✓,4.9 ✓,4.8 ✓
30,L1PA−ideal (|d|≤3),-4.7 ⚠,-5.6 ⚠,-6.4 ⚠,-5.1 ⚠
31,L4S1 (35–45),43.4 ✓,41.3 ✓,45.4 ⚠,43.1 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.4 ✓,2.4 ✓,2.2 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.4 ⚠,-5.5 ⚠,-5.4 ⚠
34,GAP Category (P),MD ⚠,P ✓,MD ⚠,MD ⚠

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.2,10.7,1.3,1.3
1,Optimization Score,0.5,1.0,1.1,1.3
2,Mech Fail Prob,2.3%,5.2%,5.6%,6.7%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,5,5
10,ALIF,0,1,0,0
11,XLIF,0,0,1,1
12,TLIF,1,1,1,0
13,num_rods,6,6,5,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,54.3,53.8,53.8
19,SS,44.4,44.8,44.3,44.3
20,L4S1,43.4,52.4,39.6,36.5
21,GlobalTilt,21.6,21.0,21.6,21.5
22,T4PA,4.9,3.8,5.5,5.2
23,L1PA,3.6,0.7,3.8,5.1
24,SVA,85.6,84.7,90.1,90.1
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,13.8,14.3,14.3
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.3 ✓,4.8 ✓,4.8 ✓
30,L1PA−ideal (|d|≤3),-4.7 ⚠,-7.6 ⚠,-4.5 ⚠,-3.2 ⚠
31,L4S1 (35–45),43.4 ✓,52.4 ⚠,39.6 ✓,36.5 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,3.1 ⚠,1.7 ✓,0.1 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-4.9 ⚠,-5.4 ⚠,-5.4 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,P ✓,P ✓

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.3,1.4,1.3,1.3
1,Optimization Score,4.4,5.2,5.5,5.7
2,Mech Fail Prob,2.8%,6.6%,8.3%,9.2%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,PS,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,3,4,2
10,ALIF,0,0,0,0
11,XLIF,0,1,0,1
12,TLIF,1,1,1,0
13,num_rods,5,6,3,6
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.8,53.7,53.7
19,SS,44.4,44.3,44.2,44.3
20,L4S1,41.6,41.3,40.9,38.1
21,GlobalTilt,21.5,21.1,21.8,21.1
22,T4PA,5.8,5.1,6.7,5.1
23,L1PA,4.6,2.7,4.4,3.9
24,SVA,87.7,84.3,82.9,84.9
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.3,14.4,14.3
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.8 ✓,4.9 ✓,4.9 ✓
30,L1PA−ideal (|d|≤3),-3.7 ⚠,-5.6 ⚠,-3.9 ⚠,-4.4 ⚠
31,L4S1 (35–45),41.6 ✓,41.3 ✓,40.9 ✓,38.1 ✓
32,T4PA−L1PA (|d|≤3),1.2 ✓,2.4 ✓,2.3 ✓,1.2 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.4 ⚠,-5.5 ⚠,-5.5 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.3,1.3,1.3,1.4
1,Optimization Score,4.5,4.7,4.7,6.1
2,Mech Fail Prob,2.8%,3.3%,3.3%,6.0%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,PS
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,5,5
10,ALIF,0,0,0,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,5,5,4,4
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.8,53.8,53.7
19,SS,44.4,44.4,44.4,43.8
20,L4S1,41.6,41.5,39.8,42.7
21,GlobalTilt,21.5,21.0,22.1,22.4
22,T4PA,5.8,6.1,6.7,5.6
23,L1PA,4.6,4.5,5.5,3.5
24,SVA,87.7,87.7,88.7,84.1
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.2,14.2,14.8
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.8 ✓,4.8 ✓,4.9 ✓
30,L1PA−ideal (|d|≤3),-3.7 ⚠,-3.8 ⚠,-2.8 ✓,-4.8 ⚠
31,L4S1 (35–45),41.6 ✓,41.5 ✓,39.8 ✓,42.7 ✓
32,T4PA−L1PA (|d|≤3),1.2 ✓,1.6 ✓,1.2 ✓,2.1 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.4 ⚠,-5.4 ⚠,-5.5 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.2,1.4,10.6,1.3
1,Optimization Score,0.7,1.4,1.5,1.5
2,Mech Fail Prob,2.3%,6.0%,6.7%,6.7%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 1 (P),12.0 (SD) → 4 (MD),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,5,4
10,ALIF,0,0,1,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,4,5,5
14,num_pelvic_screws,2,2,3,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.7,54.3,53.7
19,SS,44.4,43.8,44.8,44.5
20,L4S1,43.4,42.7,51.7,42.8
21,GlobalTilt,21.6,22.4,21.6,20.9
22,T4PA,4.9,5.6,3.8,5.2
23,L1PA,3.6,3.5,1.2,4.2
24,SVA,85.6,84.1,87.2,87.6
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.8,13.8,14.1
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.9 ✓,4.3 ✓,4.9 ✓
30,L1PA−ideal (|d|≤3),-4.7 ⚠,-4.8 ⚠,-7.1 ⚠,-4.1 ⚠
31,L4S1 (35–45),43.4 ✓,42.7 ✓,51.7 ⚠,42.8 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.1 ✓,2.6 ✓,1.0 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.5 ⚠,-4.9 ⚠,-5.5 ⚠
34,GAP Category (P),MD ⚠,P ✓,MD ⚠,P ✓

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.2,10.3,10.8,1.3
1,Optimization Score,0.5,1.0,1.1,1.3
2,Mech Fail Prob,2.3%,5.0%,5.6%,6.7%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,4,5,4
10,ALIF,0,0,1,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,5
14,num_pelvic_screws,2,2,3,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,53.8,53.7,54.3,53.7
19,SS,44.4,43.9,44.8,44.5
20,L4S1,43.4,46.2,53.4,42.8
21,GlobalTilt,21.6,21.3,21.6,20.9
22,T4PA,4.9,4.0,2.9,5.2
23,L1PA,3.6,1.5,0.2,4.2
24,SVA,85.6,81.0,85.1,87.6
25,PI,58.6,58.6,58.6,58.6
26,PT,14.2,14.7,13.8,14.1
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),4.8 ✓,4.9 ✓,4.3 ✓,4.9 ✓
30,L1PA−ideal (|d|≤3),-4.7 ⚠,-6.8 ⚠,-8.1 ⚠,-4.1 ⚠
31,L4S1 (35–45),43.4 ✓,46.2 ⚠,53.4 ⚠,42.8 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.5 ✓,2.7 ✓,1.0 ✓
33,LL−ideal (|d|≤3),-5.4 ⚠,-5.5 ⚠,-4.9 ⚠,-5.5 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,P ✓

### Actual vs. Results

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [10]:
# Build x vector for the actual surgical plan (from holdout data)
holdout_row = holdout_df[holdout_df["id"] == PATIENT_ID].iloc[0]
actual_x = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row[col]
    if var_spec.get("categorical", False):
        actual_x.append(var_spec["choices"].index(val))
    else:
        actual_x.append(int(val))
actual_x = np.array(actual_x)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval = ou.evaluate_solution(
        actual_x, patient_fixed, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed, actual_eval)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

## Test Patient 2

this is a revision patient

In [11]:
PATIENT_ID_2 = 2964021
patient_fixed_2 = ou.load_patient_data(patient_id=PATIENT_ID_2, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_2}")

Selected patient: 2964021

In [12]:
# Run all selected scenarios for Patient 2
all_results_2 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_2,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=100,
        n_gen=20,
        seed=42,
        verbose=False,
        top_n=4,
        score_tolerance=2,
    )
    all_results_2[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_2)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 2.01  |  Mech fail: 5.8%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 2.01  |  Mech fail: 2.3%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 2.92  |  Mech fail: 5.8%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 1.17  |  Mech fail: 5.8%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 0.46  |  Mech fail: 2.3%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 5.02  |  Mech fail: 5.8%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 6.00  |  Mech fail: 5.8%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 1.59  |  Mech fail: 5.8%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 0.98  |  Mech fail: 4.9%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [13]:
df_actual_2 = disp.display_actual_outcomes(
    PATIENT_ID_2, patient_fixed_2, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_2)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: PS
  num_levels_cat: lower
  num_interbody_fusion_levels: 2
  ALIF: 1
  XLIF: 0
  TLIF: 0
  num_rods: 3
  num_pelvic_screws: 3
  osteotomy (PSO): 0

  Mechanical Failure: No
  ODI: 15.0 (preop) → 0.0 (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 41.8%
  Predicted ODI (postop):        -3.9

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                    7.17
    [mech_fail]            Minimize Mechanical Failure                 29.70
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        20.92
    [l4s1]                 Minimize L4S1 Penalty                        8.46
    [t4l1pa]               Minimize T4L1PA Penalty                      8.37
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        21.61
    [odi]                  Minimize Postop ODI                          8.37
    [gap_score]            Minimize GAP Score                          12.21
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   23.99
    [ll]                   Minimize LL (PI-LL) Penalty                  8.78

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     67.2           -1.3            65.9
1                    SS     32.7            5.9            38.6
2                  L4S1     51.8           -6.6            45.2
3            GlobalTilt     19.4          -16.7             2.7
4                  T4PA      6.6          -11.8            -5.2
5                  L1PA      1.7           -6.3            -4.6
6                    PI     54.9          -10.9            44.0
7                    PT     22.2          -16.8             5.4
8                   SVA      0.0          -10.1           -10.1
9                   Age       70              -               -
10            GAP Score      3.0              -             1.0
11         GAP Category       MD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)  -12.3 ⚠           -9.6         -21.9 ⚠
14   L1PA−ideal (|d|≤3)   -4.7 ⚠           -6.3         -11.0 ⚠
15         L4S1 (35–45)   51.8 ⚠           -6.6          45.2 ⚠
16    T4PA−L1PA (|d|≤3)    4.9 ⚠           -5.5          -0.6 ✓
17     LL−ideal (|d|≤3)   10.0 ⚠           -1.3           8.7 ⚠
18          GAP Cat (P)     MD ⚠              →             P ✓

### Results

In [14]:
from IPython.display import display, Markdown

for key in SCENARIOS:
    r = all_results_2[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{runs.PRESETS[key]['description']}*"))

    # Top 4 diverse plans
    display(Markdown("**Top diverse plans:**"))
    _ = disp.display_multiple_solutions(r["diverse_df"], patient_fixed_2)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.4,1.4,1.5
1,Optimization Score,1.4,2.0,2.0,2.0
2,Mech Fail Prob,1.6%,5.6%,5.9%,5.2%
3,Predicted ODI,-22.8,-10.4,-12.0,-15.7
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,PS,Hook
8,num_levels_cat,lower,higher,lower,lower
9,num_interbody_fusion_levels,5,3,4,3
10,ALIF,0,0,0,1
11,XLIF,0,0,0,0
12,TLIF,1,1,1,0
13,num_rods,6,5,3,6
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.9,63.8,63.9
19,SS,34.4,34.3,34.3,35.2
20,L4S1,43.6,43.0,41.1,49.5
21,GlobalTilt,14.6,13.4,14.1,14.2
22,T4PA,4.5,5.1,6.3,3.4
23,L1PA,3.2,3.7,4.0,1.5
24,SVA,9.4,16.4,15.2,8.0
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,20.6,20.6,19.7
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-9.0 ⚠,-8.9 ⚠,-9.0 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-2.7 ✓,-2.4 ✓,-4.9 ⚠
31,L4S1 (35–45),43.6 ✓,43.0 ✓,41.1 ✓,49.5 ⚠
32,T4PA−L1PA (|d|≤3),1.3 ✓,1.4 ✓,2.3 ✓,1.9 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.7 ⚠,6.6 ⚠,6.7 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.4,1.4,1.6
1,Optimization Score,1.5,1.8,2.9,3.5
2,Mech Fail Prob,1.6%,1.9%,3.5%,4.3%
3,Predicted ODI,-22.8,-21.6,-13.5,-16.8
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,PS,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,5,4
10,ALIF,0,0,0,1
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,5,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.9,63.8,63.9
19,SS,34.4,34.4,34.4,35.5
20,L4S1,43.6,43.6,44.7,50.9
21,GlobalTilt,14.6,14.3,14.5,14.2
22,T4PA,4.5,4.8,4.3,4.3
23,L1PA,3.2,3.1,2.2,1.3
24,SVA,9.4,9.4,17.0,15.7
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,20.5,20.5,19.4
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-9.0 ⚠,-8.9 ⚠,-9.0 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-3.3 ⚠,-4.2 ⚠,-5.1 ⚠
31,L4S1 (35–45),43.6 ✓,43.6 ✓,44.7 ✓,50.9 ⚠
32,T4PA−L1PA (|d|≤3),1.3 ✓,1.7 ✓,2.1 ✓,3.0 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.7 ⚠,6.6 ⚠,6.7 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.4,1.6,1.4
1,Optimization Score,0.8,1.8,1.8,2.4
2,Mech Fail Prob,1.6%,3.5%,3.6%,4.7%
3,Predicted ODI,-22.8,-13.5,-18.0,-11.6
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,5,4
10,ALIF,0,0,1,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,5,5,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.8,63.9,63.9
19,SS,34.4,34.4,35.5,34.3
20,L4S1,43.6,44.7,51.0,43.1
21,GlobalTilt,14.6,14.5,14.6,13.4
22,T4PA,4.5,4.3,4.1,4.8
23,L1PA,3.2,2.2,1.4,3.8
24,SVA,9.4,17.0,15.7,17.0
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,20.5,19.4,20.6
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-8.9 ⚠,-9.0 ⚠,-9.0 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-4.2 ⚠,-5.0 ⚠,-2.6 ✓
31,L4S1 (35–45),43.6 ✓,44.7 ✓,51.0 ⚠,43.1 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.1 ✓,2.7 ✓,1.0 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.6 ⚠,6.7 ⚠,6.7 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.4,20.6,20.7
1,Optimization Score,0.3,0.7,1.1,1.4
2,Mech Fail Prob,1.6%,3.5%,5.5%,7.0%
3,Predicted ODI,-22.8,-13.5,-20.8,-14.1
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,PS
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,5,2,4
10,ALIF,0,0,0,0
11,XLIF,0,0,1,1
12,TLIF,1,1,1,1
13,num_rods,6,5,6,6
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.8,63.9,63.8
19,SS,34.4,34.4,34.2,34.2
20,L4S1,43.6,44.7,41.4,44.5
21,GlobalTilt,14.6,14.5,14.3,14.2
22,T4PA,4.5,4.3,5.0,3.3
23,L1PA,3.2,2.2,2.2,0.4
24,SVA,9.4,17.0,12.9,13.4
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,20.5,20.7,20.7
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-8.9 ⚠,-9.0 ⚠,-8.9 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-4.2 ⚠,-4.2 ⚠,-6.0 ⚠
31,L4S1 (35–45),43.6 ✓,44.7 ✓,41.4 ✓,44.5 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.1 ✓,2.8 ✓,2.9 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.6 ⚠,6.7 ⚠,6.6 ⚠
34,GAP Category (P),P ✓,P ✓,MD ⚠,MD ⚠

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,22.3,20.6,20.6
1,Optimization Score,0.3,0.7,0.8,0.9
2,Mech Fail Prob,1.6%,3.6%,3.9%,4.7%
3,Predicted ODI,-22.8,-16.9,-24.4,-24.4
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 4 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,5,5
10,ALIF,0,1,0,0
11,XLIF,0,0,1,1
12,TLIF,1,1,1,0
13,num_rods,6,6,5,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.9,63.9,63.9
19,SS,34.4,35.5,34.2,34.0
20,L4S1,43.6,52.7,39.9,36.8
21,GlobalTilt,14.6,14.2,14.6,14.5
22,T4PA,4.5,3.4,5.1,4.8
23,L1PA,3.2,0.3,3.5,4.7
24,SVA,9.4,8.6,20.2,20.2
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,19.4,20.7,20.9
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-9.0 ⚠,-9.0 ⚠,-9.0 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-6.1 ⚠,-2.9 ✓,-1.7 ✓
31,L4S1 (35–45),43.6 ✓,52.7 ⚠,39.9 ✓,36.8 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,3.1 ⚠,1.6 ✓,0.1 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.7 ⚠,6.7 ⚠,6.7 ⚠
34,GAP Category (P),P ✓,MD ⚠,MD ⚠,MD ⚠

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.4,1.4,1.6
1,Optimization Score,4.2,4.6,4.7,4.9
2,Mech Fail Prob,1.6%,4.0%,4.2%,5.1%
3,Predicted ODI,-22.8,-11.8,-11.1,-15.5
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,PS,Hook
8,num_levels_cat,lower,higher,lower,lower
9,num_interbody_fusion_levels,5,4,3,3
10,ALIF,0,0,0,1
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.9,63.8,63.9
19,SS,34.4,34.3,34.4,35.5
20,L4S1,43.6,44.9,46.4,50.8
21,GlobalTilt,14.6,13.5,14.1,14.2
22,T4PA,4.5,3.9,3.9,4.6
23,L1PA,3.2,2.8,1.0,1.2
24,SVA,9.4,9.8,9.3,15.2
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,20.6,20.5,19.4
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-9.0 ⚠,-8.9 ⚠,-9.0 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-3.6 ⚠,-5.4 ⚠,-5.2 ⚠
31,L4S1 (35–45),43.6 ✓,44.9 ✓,46.4 ⚠,50.8 ⚠
32,T4PA−L1PA (|d|≤3),1.3 ✓,1.1 ✓,2.9 ✓,3.4 ⚠
33,LL−ideal (|d|≤3),6.7 ⚠,6.7 ⚠,6.6 ⚠,6.7 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.4,1.6,1.4
1,Optimization Score,3.9,5.2,5.2,5.4
2,Mech Fail Prob,1.6%,4.2%,4.3%,4.7%
3,Predicted ODI,-22.8,-12.2,-16.8,-10.5
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,4,4,3
10,ALIF,0,0,1,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,5,5,6
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.8,63.9,63.9
19,SS,34.4,34.4,35.5,34.3
20,L4S1,43.6,44.7,50.9,44.8
21,GlobalTilt,14.6,14.1,14.2,13.5
22,T4PA,4.5,4.5,4.3,4.2
23,L1PA,3.2,2.1,1.3,2.7
24,SVA,9.4,17.0,15.7,9.2
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,20.5,19.4,20.6
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-8.9 ⚠,-9.0 ⚠,-9.0 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-4.3 ⚠,-5.1 ⚠,-3.7 ⚠
31,L4S1 (35–45),43.6 ✓,44.7 ✓,50.9 ⚠,44.8 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.4 ✓,3.0 ✓,1.5 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.6 ⚠,6.7 ⚠,6.7 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.4,20.6,20.6
1,Optimization Score,0.8,1.4,1.8,1.9
2,Mech Fail Prob,1.6%,5.0%,6.6%,7.4%
3,Predicted ODI,-22.8,-13.2,-23.0,-19.3
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,FS
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,5,4,5
10,ALIF,0,0,0,0
11,XLIF,0,0,1,0
12,TLIF,1,1,0,1
13,num_rods,6,3,4,5
14,num_pelvic_screws,2,2,2,3
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.8,63.9,63.8
19,SS,34.4,34.3,34.0,33.7
20,L4S1,43.6,41.2,35.0,43.4
21,GlobalTilt,14.6,14.4,14.1,13.9
22,T4PA,4.5,6.1,6.0,5.0
23,L1PA,3.2,4.1,5.6,2.9
24,SVA,9.4,15.2,20.2,13.5
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,20.6,20.9,21.2
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-8.9 ⚠,-9.0 ⚠,-8.9 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-2.3 ✓,-0.8 ✓,-3.5 ⚠
31,L4S1 (35–45),43.6 ✓,41.2 ✓,35.0 ✓,43.4 ✓
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.0 ✓,0.4 ✓,2.1 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.6 ⚠,6.7 ⚠,6.6 ⚠
34,GAP Category (P),P ✓,P ✓,MD ⚠,MD ⚠

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.4,1.6,1.4,20.6
1,Optimization Score,0.3,0.7,1.0,1.2
2,Mech Fail Prob,1.6%,3.6%,5.0%,6.1%
3,Predicted ODI,-22.8,-18.0,-12.1,-11.2
4,GAP Score,3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,PS,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,4,3
10,ALIF,0,1,0,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,5,4,6
14,num_pelvic_screws,2,2,2,3
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,63.9,63.9,63.8,63.8
19,SS,34.4,35.5,34.4,34.0
20,L4S1,43.6,51.0,42.9,45.8
21,GlobalTilt,14.6,14.6,14.1,13.1
22,T4PA,4.5,4.1,5.4,3.5
23,L1PA,3.2,1.4,3.1,2.2
24,SVA,9.4,15.7,17.9,6.8
25,PI,54.9,54.9,54.9,54.9
26,PT,20.5,19.4,20.5,20.9
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-9.0 ⚠,-9.0 ⚠,-8.9 ⚠,-8.9 ⚠
30,L1PA−ideal (|d|≤3),-3.2 ⚠,-5.0 ⚠,-3.3 ⚠,-4.2 ⚠
31,L4S1 (35–45),43.6 ✓,51.0 ⚠,42.9 ✓,45.8 ⚠
32,T4PA−L1PA (|d|≤3),1.3 ✓,2.7 ✓,2.3 ✓,1.3 ✓
33,LL−ideal (|d|≤3),6.7 ⚠,6.7 ⚠,6.6 ⚠,6.6 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,MD ⚠

### Actual vs. Results

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [15]:
# Build x vector for the actual surgical plan (Patient 2)
holdout_row_2 = holdout_df[holdout_df["id"] == PATIENT_ID_2].iloc[0]
actual_x_2 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_2[col]
    if var_spec.get("categorical", False):
        actual_x_2.append(var_spec["choices"].index(val))
    else:
        actual_x_2.append(int(val))
actual_x_2 = np.array(actual_x_2)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results_2[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval_2 = ou.evaluate_solution(
        actual_x_2, patient_fixed_2, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_2, actual_eval_2)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

## Test Patient 3

In [16]:
PATIENT_ID_3 = 818588
patient_fixed_3 = ou.load_patient_data(patient_id=PATIENT_ID_3, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_3}")

Selected patient: 818588

In [17]:
# Run all selected scenarios for Patient 3
all_results_3 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_3,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=100,
        n_gen=20,
        seed=42,
        verbose=False,
        top_n=4,
        score_tolerance=2,
    )
    all_results_3[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_3)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 8.10  |  Mech fail: 2.1%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 3.17  |  Mech fail: 0.7%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 0.75  |  Mech fail: 1.5%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 0.31  |  Mech fail: 0.9%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 0.14  |  Mech fail: 0.7%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 20.96  |  Mech fail: 2.1%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 12.57  |  Mech fail: 0.7%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 0.71  |  Mech fail: 2.3%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 0.35  |  Mech fail: 1.8%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [18]:
df_actual_3 = disp.display_actual_outcomes(
    PATIENT_ID_3, patient_fixed_3, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_3)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: PS
  num_levels_cat: lower
  num_interbody_fusion_levels: 1
  ALIF: 0
  XLIF: 0
  TLIF: 1
  num_rods: 3
  num_pelvic_screws: 2
  osteotomy (PSO): 0

  Mechanical Failure: Yes
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 7.5%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                    8.99
    [mech_fail]            Minimize Mechanical Failure                  8.04
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA         3.86
    [l4s1]                 Minimize L4S1 Penalty                        2.38
    [t4l1pa]               Minimize T4L1PA Penalty                      1.67
    [equal_plus_mech]      Equal Alignment + Mechanical Failure         8.38
    [odi]                  Minimize Postop ODI                          1.51
    [gap_score]            Minimize GAP Score                          22.04
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   16.00
    [ll]                   Minimize LL (PI-LL) Penalty                  2.10

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     16.6           18.0            34.6
1                    SS     16.6              -               -
2                  L4S1     26.6            1.4            28.0
3            GlobalTilt     21.9           -9.6            12.3
4                  T4PA     14.0           -8.0             6.0
5                  L1PA      6.8           -5.0             1.8
6                    PI     38.2           -2.5            35.7
7                    PT     21.6           -5.6            16.0
8                   SVA     15.9          -15.9             0.0
9                   Age       78              -               -
10            GAP Score     12.0              -            10.0
11         GAP Category       SD              →              SD
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   21.6 ⚠          -20.5           1.1 ✓
14   L1PA−ideal (|d|≤3)    8.7 ⚠           -5.0           3.7 ⚠
15         L4S1 (35–45)   26.6 ⚠            1.4          28.0 ⚠
16    T4PA−L1PA (|d|≤3)    7.2 ⚠           -3.0           4.2 ⚠
17     LL−ideal (|d|≤3)  -31.6 ⚠           18.0         -13.6 ⚠
18          GAP Cat (P)     SD ⚠              →            SD ⚠

### Results

In [19]:
from IPython.display import display, Markdown

for key in SCENARIOS:
    r = all_results_3[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{runs.PRESETS[key]['description']}*"))

    # Top 4 diverse plans
    display(Markdown("**Top diverse plans:**"))
    _ = disp.display_multiple_solutions(r["diverse_df"], patient_fixed_3)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,8.9,8.9,9.0,9.0
1,Optimization Score,7.7,7.9,7.9,8.0
2,Mech Fail Prob,0.6%,1.4%,1.2%,2.0%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,higher,lower,lower
9,num_interbody_fusion_levels,4,4,4,5
10,ALIF,0,0,0,0
11,XLIF,0,0,1,1
12,TLIF,1,1,1,0
13,num_rods,6,5,6,6
14,num_pelvic_screws,2,2,2,4
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.2,42.4,42.2,42.5
19,SS,21.7,21.8,21.7,21.4
20,L4S1,33.7,33.3,31.7,30.7
21,GlobalTilt,8.5,8.1,8.5,8.7
22,T4PA,4.8,4.8,4.5,2.7
23,L1PA,1.7,2.4,1.0,1.2
24,SVA,15.4,26.1,18.2,18.5
25,PI,38.2,38.2,38.2,38.2
26,PT,16.5,16.4,16.5,16.8
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.0 ⚠,-4.2 ⚠,-4.0 ⚠,-4.3 ⚠
30,L1PA−ideal (|d|≤3),3.6 ⚠,4.3 ⚠,2.9 ✓,3.1 ⚠
31,L4S1 (35–45),33.7 ⚠,33.3 ⚠,31.7 ⚠,30.7 ⚠
32,T4PA−L1PA (|d|≤3),3.1 ⚠,2.4 ✓,3.5 ⚠,1.5 ✓
33,LL−ideal (|d|≤3),-6.0 ⚠,-5.8 ⚠,-6.0 ⚠,-5.7 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,8.9,9.1,9.0,9.1
1,Optimization Score,3.1,3.7,3.9,4.0
2,Mech Fail Prob,0.6%,1.4%,1.7%,1.8%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,FS,PS
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,4,4,5,4
10,ALIF,0,0,0,0
11,XLIF,0,1,0,0
12,TLIF,1,1,1,1
13,num_rods,6,5,5,3
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.2,42.2,41.5,41.0
19,SS,21.7,21.7,20.9,22.0
20,L4S1,33.7,30.0,32.6,31.3
21,GlobalTilt,8.5,8.4,9.3,8.6
22,T4PA,4.8,5.4,5.7,6.4
23,L1PA,1.7,2.0,2.0,2.6
24,SVA,15.4,29.0,27.5,26.4
25,PI,38.2,38.2,38.2,38.2
26,PT,16.5,16.5,17.3,16.2
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.0 ⚠,-4.0 ⚠,-3.3 ⚠,-2.8 ⚠
30,L1PA−ideal (|d|≤3),3.6 ⚠,3.9 ⚠,3.9 ⚠,4.5 ⚠
31,L4S1 (35–45),33.7 ⚠,30.0 ⚠,32.6 ⚠,31.3 ⚠
32,T4PA−L1PA (|d|≤3),3.1 ⚠,3.4 ⚠,3.7 ⚠,3.8 ⚠
33,LL−ideal (|d|≤3),-6.0 ⚠,-6.0 ⚠,-6.7 ⚠,-7.2 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,12.8,12.8,12.8,8.9
1,Optimization Score,0.2,0.5,0.5,0.8
2,Mech Fail Prob,0.5%,0.9%,0.9%,1.7%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,5,3
10,ALIF,0,0,1,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.2,41.0,42.5,42.4
19,SS,21.7,21.4,22.9,21.7
20,L4S1,33.8,36.7,42.9,33.2
21,GlobalTilt,9.1,9.3,8.7,8.1
22,T4PA,4.6,3.4,3.2,5.1
23,L1PA,1.8,-0.2,-1.0,2.3
24,SVA,15.4,16.2,15.4,24.7
25,PI,38.2,38.2,38.2,38.2
26,PT,16.5,16.8,15.3,16.5
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.0 ⚠,-2.8 ⚠,-4.3 ⚠,-4.2 ⚠
30,L1PA−ideal (|d|≤3),3.7 ⚠,1.7 ✓,0.9 ✓,4.2 ⚠
31,L4S1 (35–45),33.8 ⚠,36.7 ✓,42.9 ✓,33.2 ⚠
32,T4PA−L1PA (|d|≤3),2.8 ✓,3.6 ⚠,4.2 ⚠,2.8 ✓
33,LL−ideal (|d|≤3),-6.0 ⚠,-7.2 ⚠,-5.7 ⚠,-5.8 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,12.7,12.8,12.8,12.7
1,Optimization Score,0.1,0.2,0.2,0.2
2,Mech Fail Prob,0.6%,0.9%,0.9%,1.0%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,5,5
10,ALIF,0,0,1,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,6
14,num_pelvic_screws,3,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.5,41.0,42.5,42.4
19,SS,21.6,21.4,22.9,21.8
20,L4S1,34.8,36.7,42.9,35.1
21,GlobalTilt,8.8,9.3,8.7,8.8
22,T4PA,3.9,3.4,3.2,3.7
23,L1PA,1.3,-0.2,-1.0,1.5
24,SVA,15.7,16.2,15.4,15.4
25,PI,38.2,38.2,38.2,38.2
26,PT,16.6,16.8,15.3,16.4
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.3 ⚠,-2.8 ⚠,-4.3 ⚠,-4.2 ⚠
30,L1PA−ideal (|d|≤3),3.2 ⚠,1.7 ✓,0.9 ✓,3.4 ⚠
31,L4S1 (35–45),34.8 ⚠,36.7 ✓,42.9 ✓,35.1 ✓
32,T4PA−L1PA (|d|≤3),2.6 ✓,3.6 ⚠,4.2 ⚠,2.2 ✓
33,LL−ideal (|d|≤3),-5.7 ⚠,-7.2 ⚠,-5.7 ⚠,-5.8 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,12.8,12.8,12.8,9.1
1,Optimization Score,0.1,0.2,0.3,0.3
2,Mech Fail Prob,0.5%,1.0%,1.1%,1.4%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,5,5,4
10,ALIF,0,0,1,0
11,XLIF,0,0,0,1
12,TLIF,1,1,1,1
13,num_rods,6,5,5,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.2,41.0,42.5,42.2
19,SS,21.7,21.4,22.9,21.7
20,L4S1,33.8,34.9,41.1,30.0
21,GlobalTilt,9.1,9.3,8.7,8.4
22,T4PA,4.6,4.3,4.1,5.4
23,L1PA,1.8,0.8,-0.0,2.0
24,SVA,15.4,27.0,26.2,29.0
25,PI,38.2,38.2,38.2,38.2
26,PT,16.5,16.8,15.3,16.5
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.0 ⚠,-2.8 ⚠,-4.3 ⚠,-4.0 ⚠
30,L1PA−ideal (|d|≤3),3.7 ⚠,2.7 ✓,1.9 ✓,3.9 ⚠
31,L4S1 (35–45),33.8 ⚠,34.9 ⚠,41.1 ✓,30.0 ⚠
32,T4PA−L1PA (|d|≤3),2.8 ✓,3.5 ⚠,4.1 ⚠,3.4 ⚠
33,LL−ideal (|d|≤3),-6.0 ⚠,-7.2 ⚠,-5.7 ⚠,-6.0 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,8.9,9.2,9.2,9.1
1,Optimization Score,20.6,20.8,20.9,20.9
2,Mech Fail Prob,0.6%,1.4%,1.7%,1.8%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,PS
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,4,5,3,4
10,ALIF,0,0,0,0
11,XLIF,0,1,1,0
12,TLIF,1,1,0,1
13,num_rods,6,4,6,3
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.2,42.2,42.2,41.0
19,SS,21.7,21.7,21.4,22.0
20,L4S1,33.7,28.3,28.6,31.3
21,GlobalTilt,8.5,9.1,8.4,8.6
22,T4PA,4.8,6.1,4.5,6.4
23,L1PA,1.7,3.0,2.2,2.6
24,SVA,15.4,30.0,16.7,26.4
25,PI,38.2,38.2,38.2,38.2
26,PT,16.5,16.5,16.8,16.2
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.0 ⚠,-4.0 ⚠,-4.0 ⚠,-2.8 ⚠
30,L1PA−ideal (|d|≤3),3.6 ⚠,4.9 ⚠,4.1 ⚠,4.5 ⚠
31,L4S1 (35–45),33.7 ⚠,28.3 ⚠,28.6 ⚠,31.3 ⚠
32,T4PA−L1PA (|d|≤3),3.1 ⚠,3.1 ⚠,2.3 ✓,3.8 ⚠
33,LL−ideal (|d|≤3),-6.0 ⚠,-6.0 ⚠,-6.0 ⚠,-7.2 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,8.9,9.0,9.2,9.1
1,Optimization Score,12.5,12.7,12.8,13.3
2,Mech Fail Prob,0.6%,1.0%,1.2%,2.1%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,4,5,5,0
10,ALIF,0,0,0,0
11,XLIF,0,1,1,0
12,TLIF,1,1,0,0
13,num_rods,6,6,6,5
14,num_pelvic_screws,2,2,2,3
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.2,42.2,42.2,42.5
19,SS,21.7,21.7,21.4,20.9
20,L4S1,33.7,31.8,28.7,29.6
21,GlobalTilt,8.5,9.1,9.1,9.1
22,T4PA,4.8,4.3,3.9,5.9
23,L1PA,1.7,1.1,2.3,3.1
24,SVA,15.4,18.2,18.2,24.3
25,PI,38.2,38.2,38.2,38.2
26,PT,16.5,16.5,16.8,17.3
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.0 ⚠,-4.0 ⚠,-4.0 ⚠,-4.3 ⚠
30,L1PA−ideal (|d|≤3),3.6 ⚠,3.0 ✓,4.2 ⚠,5.0 ⚠
31,L4S1 (35–45),33.7 ⚠,31.8 ⚠,28.7 ⚠,29.6 ⚠
32,T4PA−L1PA (|d|≤3),3.1 ⚠,3.2 ⚠,1.6 ✓,2.8 ✓
33,LL−ideal (|d|≤3),-6.0 ⚠,-6.0 ⚠,-6.0 ⚠,-5.7 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,12.7,12.8,8.9,9.4
1,Optimization Score,0.4,0.4,0.6,0.6
2,Mech Fail Prob,0.6%,0.9%,1.7%,1.7%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,higher,lower
9,num_interbody_fusion_levels,5,5,3,4
10,ALIF,0,1,0,0
11,XLIF,0,0,0,1
12,TLIF,1,1,1,0
13,num_rods,6,6,5,5
14,num_pelvic_screws,3,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.5,42.5,42.4,42.2
19,SS,21.6,22.9,21.7,21.4
20,L4S1,34.8,42.9,33.2,26.9
21,GlobalTilt,8.8,8.7,8.1,8.4
22,T4PA,3.9,3.2,5.1,5.1
23,L1PA,1.3,-1.0,2.3,3.2
24,SVA,15.7,15.4,24.7,29.0
25,PI,38.2,38.2,38.2,38.2
26,PT,16.6,15.3,16.5,16.8
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.3 ⚠,-4.3 ⚠,-4.2 ⚠,-4.0 ⚠
30,L1PA−ideal (|d|≤3),3.2 ⚠,0.9 ✓,4.2 ⚠,5.1 ⚠
31,L4S1 (35–45),34.8 ⚠,42.9 ✓,33.2 ⚠,26.9 ⚠
32,T4PA−L1PA (|d|≤3),2.6 ✓,4.2 ⚠,2.8 ✓,1.9 ✓
33,LL−ideal (|d|≤3),-5.7 ⚠,-5.7 ⚠,-5.8 ⚠,-6.0 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,12.8,12.8,12.7,8.9
1,Optimization Score,0.1,0.2,0.2,0.3
2,Mech Fail Prob,0.5%,1.0%,1.2%,1.4%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,4,5,4
10,ALIF,0,0,1,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,5
14,num_pelvic_screws,2,2,3,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,42.2,41.0,42.7,42.4
19,SS,21.7,21.4,22.8,21.8
20,L4S1,33.8,36.6,43.9,33.3
21,GlobalTilt,9.1,8.6,8.3,8.1
22,T4PA,4.6,3.7,2.6,4.8
23,L1PA,1.8,-0.3,-1.5,2.4
24,SVA,15.4,16.2,15.7,26.1
25,PI,38.2,38.2,38.2,38.2
26,PT,16.5,16.8,15.4,16.4
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),-4.0 ⚠,-2.8 ⚠,-4.5 ⚠,-4.2 ⚠
30,L1PA−ideal (|d|≤3),3.7 ⚠,1.6 ✓,0.4 ✓,4.3 ⚠
31,L4S1 (35–45),33.8 ⚠,36.6 ✓,43.9 ✓,33.3 ⚠
32,T4PA−L1PA (|d|≤3),2.8 ✓,4.0 ⚠,4.1 ⚠,2.4 ✓
33,LL−ideal (|d|≤3),-6.0 ⚠,-7.2 ⚠,-5.5 ⚠,-5.8 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Actual vs. Results

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [20]:
# Build x vector for the actual surgical plan (Patient 3)
holdout_row_3 = holdout_df[holdout_df["id"] == PATIENT_ID_3].iloc[0]
actual_x_3 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_3[col]
    if var_spec.get("categorical", False):
        actual_x_3.append(var_spec["choices"].index(val))
    else:
        actual_x_3.append(int(val))
actual_x_3 = np.array(actual_x_3)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results_3[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval_3 = ou.evaluate_solution(
        actual_x_3, patient_fixed_3, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_3, actual_eval_3)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*