# Optimization

## Import Libraries

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

import importlib
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

from src import config
import src.optimization_utils as ou
import src.solutions as s
import src.display as disp
import src.runs as runs
from src.problem import SpineProblem

# Reload to pick up any changes
importlib.reload(ou)
importlib.reload(s)
importlib.reload(disp)
importlib.reload(runs)

pd.set_option('display.max_columns', None)

In [2]:
# =============================================================================
# GA Configuration
# =============================================================================
POP_SIZE  = 100   # GA population size
N_GEN     = 20    # Number of generations
SEED      = 42    # Random seed for reproducibility
TOP_N     = 4     # Number of diverse solutions to display
SCORE_TOL = 5     # Score window around best for diversity selection

PSO_LL_OVERRIDE = False  # Toggle clinical delta_LL correction for literature ranges
DEDUP_BEST = True          # Deduplicate best plans across scenarios

## Load Models

In [3]:
# Load all models
model_configs = {
    "Mechanical Failure": config.MECH_FAIL_MODEL,
    "L4S1": config.L4S1_MODEL,
    "LL": config.LL_MODEL,
    "T4PA": config.T4PA_MODEL,
    "L1PA": config.L1PA_MODEL,
    "SVA": config.SVA_MODEL,
    "SS": config.SS_MODEL,
    "Global Tilt": config.GLOBAL_TILT_MODEL,
    "ODI": config.ODI_MODEL,
}

bundles = {name: ou.load_model_bundle(path) for name, path in model_configs.items()}

# Verify and display
print("Models loaded and verified:")
for name, bundle in bundles.items():
    status = "✓" if all(k in bundle for k in ["pipe", "features", "target"]) else "✗"
    print(f"  {status} {name}: {bundle.get('model_name', 'N/A')}")

# Extract individual bundles for use
mech_fail_bundle = bundles["Mechanical Failure"]
L4S1_bundle = bundles["L4S1"]
LL_bundle = bundles["LL"]
T4PA_bundle = bundles["T4PA"]
L1PA_bundle = bundles["L1PA"]
SVA_bundle = bundles["SVA"]
SS_bundle = bundles["SS"]
GT_bundle = bundles["Global Tilt"]
ODI_bundle = bundles["ODI"]

# Delta model bundles for postop predictions
delta_bundles = {
    "L4S1": L4S1_bundle,
    "LL": LL_bundle,
    "T4PA": T4PA_bundle,
    "L1PA": L1PA_bundle,
    "SS": SS_bundle,
    "GlobalTilt": GT_bundle,
    "SVA": SVA_bundle,
}

Models loaded and verified:
  ✓ Mechanical Failure: mech_fail_logreg
  ✓ L4S1: Ridge
  ✓ LL: RandomForest
  ✓ T4PA: Ridge
  ✓ L1PA: Ridge
  ✓ SVA: XGBRegressor
  ✓ SS: XGBRegressor
  ✓ Global Tilt: XGBRegressor
  ✓ ODI: Ridge

### Solution Space (Decision Variable Bounds)

In [4]:
UIV_CHOICES, xl, xu = ou.get_decision_config()

# Build a formatted solution space table
bounds_df = pd.DataFrame(
    {"Lower Bound": xl, "Upper Bound": xu},
    index=config.DECISION_VAR_NAMES,
)

# Add a "Type" column and decode categorical bounds
var_types = []
for spec in config.DECISION_VAR_SPECS:
    if spec.get("categorical"):
        var_types.append(f"Categorical: {spec['choices']}")
    elif spec["upper"] == 1:
        var_types.append("Binary (0/1)")
    else:
        var_types.append("Integer")
bounds_df.insert(0, "Type", var_types)

display(Markdown("**Decision Variable Bounds**"))
display(bounds_df)

**Decision Variable Bounds**

,Type,Lower Bound,Upper Bound
uiv_code,"Categorical: ['Hook', 'PS', 'FS']",0,2
num_levels_cat_code,"Categorical: ['lower', 'higher']",0,1
num_interbody_fusion_levels,Integer,0,5
ALIF,Binary (0/1),0,1
XLIF,Binary (0/1),0,1
TLIF,Binary (0/1),0,1
num_rods,Integer,1,4
num_pelvic_screws,Integer,2,4
osteotomy,Binary (0/1),0,1

## Optimization Scenarios

Each scenario uses a different set of composite score weights to explore how the optimizer behaves under different objectives. Predefined presets are in `src/runs.py`. To add a new scenario, add a new entry to `runs.PRESETS` and include its key below.

In [5]:
# =============================================================================
# SELECT SCENARIOS TO RUN
# =============================================================================
# Available presets (defined in src/runs.py):
#   "equal"           - All 6 alignment components weighted equally
#   "mech_fail"       - Primarily mech failure, small alignment weights
#   "mech_fail_t4l1pa"- Mech failure + T4PA-L1PA mismatch
#   "l4s1"            - Primarily L4-S1 in ideal range
#   "t4l1pa"          - Primarily T4PA-L1PA mismatch
#   "equal_plus_mech" - Composite (equal) blended 50/50 with mech failure
#   "odi"             - Primarily lowest predicted postop ODI
#   "gap_score"       - Primarily GAP score + category improvement
#   "gap_score_mech_fail" - GAP score + Mechanical Failure
#   "ll"              - Primarily PI-LL mismatch
#
# To add a new scenario: add an entry to runs.PRESETS in src/runs.py,
# then include its key here.

SCENARIOS = ["equal", "mech_fail", "mech_fail_t4l1pa", "l4s1", "t4l1pa", "gap_score", "gap_score_mech_fail", "ll", "odi"]

# Show selected scenarios
for key in SCENARIOS:
    runs.print_preset(runs.PRESETS[key])

============================================================
  Equal Weights (Composite)
  All 6 alignment components and mechanical failure weighted equally
============================================================
                       GAP Score: 0.1429 ◀
                    L1PA penalty: 0.1429 ◀
                    L4S1 penalty: 0.1429 ◀
                  T4L1PA penalty: 0.1429 ◀
                      LL penalty: 0.1429 ◀
        GAP category improvement: 0.1429 ◀
         Mechanical failure prob: 0.1429 ◀

============================================================
  Minimize Mechanical Failure
  Primarily mechanical failure probability, with small alignment weights
============================================================
                       GAP Score: 0.0500 ◀
                    L1PA penalty: 0.0500 ◀
                    L4S1 penalty: 0.0500 ◀
                  T4L1PA penalty: 0.0500 ◀
                      LL penalty: 0.0500 ◀
        GAP category improvement: 0.0500 ◀
         Mechanical failure prob: 0.7000 ◀

============================================================
  Minimize Mechanical Failure + T4L1PA
  Mechanical failure probability and T4PA-L1PA mismatch weighted equally
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.5000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize L4S1 Penalty
  Primarily L4-S1 in ideal range (35-45°), with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.8000 ◀
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize T4L1PA Penalty
  Primarily T4PA-L1PA mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.8000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.5000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.3000 ◀
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score and Mechanical Failure
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.4000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.1000 ◀
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize LL (PI-LL) Penalty
  Primarily PI-LL mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.8000 ◀
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize Postop ODI
  Primarily lowest predicted postoperative ODI, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀
                      ODI postop: 0.8000 ◀

## Test Patient 1

In [6]:
# Show holdout patients summary
holdout_df = pd.read_csv(config.DATA_HOLDOUT)

summary_cols = [
    'sex', 'age', 'ASA_CLASS',
    "id", "description", "revision", "mech_fail_last",
    "gap_score_preop", "gap_category", "gap_score_postop", "gap_category_postop",
    "UIV_implant", "num_levels_cat", "num_interbody_fusion_levels",
    "ALIF", "XLIF", "TLIF", "num_rods", "num_pelvic_screws", "osteotomy",
    "ODI_preop"
]
display(holdout_df[summary_cols].set_index("id"))

# Select patient
PATIENT_ID = 6380632
patient_fixed = ou.load_patient_data(patient_id=PATIENT_ID, data_path=config.DATA_HOLDOUT)
print(f"\nSelected patient: {PATIENT_ID}")

,sex,age,ASA_CLASS,description,revision,mech_fail_last,gap_score_preop,gap_category,gap_score_postop,gap_category_postop,UIV_implant,num_levels_cat,num_interbody_fusion_levels,ALIF,XLIF,TLIF,num_rods,num_pelvic_screws,osteotomy,ODI_preop
id,,,,,,,,,,,,,,,,,,,,
818588,MALE,78,2.0,mech failure - small GAP improvement;,0,1.0,12.0,SD,10.0,SD,PS,lower,1,0,0,1,3,2,0,NaN
1176294,MALE,71,NaN,mech failure - large GAP improvement;,1,1.0,10.0,SD,1.0,P,FS,lower,1,1,1,0,4,2,1,NaN
2964021,FEMALE,70,3.0,revision - GAP improvement 3 to 1,0,0.0,3.0,MD,1.0,P,PS,lower,2,1,0,0,3,3,0,15.0
6380632,FEMALE,76,3.0,large GAP imporovement,0,0.0,12.0,SD,1.0,P,Hook,higher,2,1,0,0,3,2,0,NaN

Selected patient: 6380632

**Run GA for all scenarios**

For each selected scenario, runs the GA optimizer and collects results. 

**Constraints (all scenarios):** 
- If `num_interbody_fusion_levels = 0`, then `ALIF = XLIF = TLIF = 0`.
- `num_interbody_fusion_levels` must be ≥ the sum of selected fusion types (`ALIF + XLIF + TLIF`).

In [7]:
all_results = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
        pso_ll_override=PSO_LL_OVERRIDE,
    )
    if result is None:
        continue
    all_results[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 8.60  |  Mech fail: 51.8%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 35.56  |  Mech fail: 50.2%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 25.10  |  Mech fail: 50.2%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 10.04  |  Mech fail: 50.2%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 10.04  |  Mech fail: 50.2%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 14.19  |  Mech fail: 51.7%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 28.18  |  Mech fail: 50.2%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 10.40  |  Mech fail: 51.0%

▶ Running: Minimize Postop ODI...
  ⚠ Skipped: patient has no preop ODI

============================================================
Completed 8 scenarios.

### Actual surgical plan/outcome

In [8]:
df_actual = disp.display_actual_outcomes(
    PATIENT_ID, patient_fixed, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: Hook
  num_levels_cat: higher
  num_interbody_fusion_levels: 2
  ALIF: 1
  XLIF: 0
  TLIF: 0
  num_rods: 3
  num_pelvic_screws: 2
  osteotomy (PSO): 0

  Mechanical Failure: No
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 62.5%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   18.74
    [mech_fail]            Minimize Mechanical Failure                 47.15
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        31.23
    [l4s1]                 Minimize L4S1 Penalty                       12.52
    [t4l1pa]               Minimize T4L1PA Penalty                     12.49
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        36.95
    [odi]                  Minimize Postop ODI                         12.49
    [gap_score]            Minimize GAP Score                          40.72
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   49.61
    [ll]                   Minimize LL (PI-LL) Penalty                 12.65

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     30.4           32.5            62.9
1                    SS     33.8           11.5            45.3
2                  L4S1     34.5            7.0            41.5
3            GlobalTilt     42.2          -23.9            18.3
4                  T4PA     24.8          -15.2             9.6
5                  L1PA     12.2           -4.8             7.4
6                    PI     58.6            2.2            60.8
7                    PT     24.8           -9.3            15.5
8                   SVA    154.6         -124.8            29.8
9                   Age       76              -               -
10            GAP Score     12.0              -             1.0
11         GAP Category       SD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   28.2 ⚠          -30.3          -2.1 ⚠
14   L1PA−ideal (|d|≤3)    3.9 ⚠           -4.8          -0.9 ✓
15         L4S1 (35–45)   34.5 ⚠            7.0          41.5 ✓
16    T4PA−L1PA (|d|≤3)   12.6 ⚠          -10.4           2.2 ✓
17     LL−ideal (|d|≤3)  -28.8 ⚠           32.5           3.7 ⚠
18          GAP Cat (P)     SD ⚠              →             P ✓

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [9]:
# Build x vector for the actual surgical plan (from holdout data)
holdout_row = holdout_df[holdout_df["id"] == PATIENT_ID].iloc[0]
actual_x = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row[col]
    if var_spec.get("categorical", False):
        actual_x.append(var_spec["choices"].index(val))
    else:
        actual_x.append(int(val))
actual_x = np.array(actual_x)

disp.display_patient_preop(patient_fixed, patient_id=PATIENT_ID)

# Evaluate actual plan using real postop values from holdout data
actual_eval = ou.evaluate_actual_plan(
    actual_x, patient_fixed, holdout_row, mech_fail_bundle
)
disp.display_best_per_scenario(all_results, patient_fixed, actual_eval, SCENARIOS, deduplicate=DEDUP_BEST)

**Patient 6380632 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty
0,Alignment Score,1.3,1.4,1.4,1.4,2.6,2.6,1.4,1.4,10.5
1,Optimization Score,1.3,8.6,35.6,25.1,10.2,10.2,14.2,28.2,10.4
2,Mech Fail Prob,62.5%,51.8%,50.2%,50.3%,50.8%,50.9%,51.7%,50.2%,51.0%
3,Predicted ODI,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 2 (P),12.0 (SD) → 2 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,
7,UIV_implant,Hook,FS,FS,FS,FS,FS,FS,FS,FS
8,num_levels_cat,higher,lower,higher,lower,higher,lower,higher,higher,lower
9,num_interbody_fusion_levels,2,1,0,0,0,0,1,0,1
10,ALIF,1,0,0,0,0,0,0,0,1
11,XLIF,0,1,0,0,0,0,1,0,0
12,TLIF,0,0,0,0,0,0,0,0,0
13,num_rods,3,4,4,4,4,4,4,4,4
14,num_pelvic_screws,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),0,1,1,1,0,0,1,1,1
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,
18,LL,62.9,53.3,53.0,53.1,53.0,53.2,53.1,53.0,53.8
19,SS,45.3,44.3,44.5,44.4,44.5,44.4,44.4,44.5,44.3
20,L4S1,41.5,37.9,40.0,40.1,35.3,35.4,37.8,40.0,49.4
21,GlobalTilt,18.3,23.0,23.0,23.0,25.0,25.0,23.0,23.0,23.1
22,T4PA,9.6,2.9,2.7,3.4,8.7,9.4,2.2,2.7,1.0
23,L1PA,7.4,2.2,2.7,2.9,6.9,7.1,2.0,2.7,-0.2
24,SVA,29.8,84.2,82.6,82.8,89.7,89.8,84.1,82.6,81.7
25,PI,58.6,58.6,58.6,58.6,58.6,58.6,58.6,58.6,58.6
26,PT,13.3,14.3,14.1,14.2,14.1,14.2,14.2,14.1,14.3
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,
29,PI-LL (0–10),-4.3 ⚠,5.3 ✓,5.6 ✓,5.5 ✓,5.6 ✓,5.4 ✓,5.5 ✓,5.6 ✓,4.8 ✓
30,L1PA−ideal (|d|≤3),-0.9 ✓,-6.1 ⚠,-5.6 ⚠,-5.4 ⚠,-1.4 ✓,-1.2 ✓,-6.3 ⚠,-5.6 ⚠,-8.5 ⚠
31,L4S1 (35–45),41.5 ✓,37.9 ✓,40.0 ✓,40.1 ✓,35.3 ✓,35.4 ✓,37.8 ✓,40.0 ✓,49.4 ⚠
32,T4PA−L1PA (|d|≤3),2.2 ✓,0.6 ✓,-0.1 ✓,0.5 ✓,1.8 ✓,2.3 ✓,0.1 ✓,-0.1 ✓,1.1 ✓
33,LL−ideal (|d|≤3),3.7 ⚠,-6.0 ⚠,-6.2 ⚠,-6.1 ⚠,-6.2 ⚠,-6.0 ⚠,-6.1 ⚠,-6.2 ⚠,-5.5 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,MD ⚠

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [10]:
# Evaluate actual plan once (real postop values don't change with weights)
actual_eval = ou.evaluate_actual_plan(
    actual_x, patient_fixed, holdout_row, mech_fail_bundle
)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    if key not in all_results:
        continue
    r = all_results[key]
    preset = runs.PRESETS[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed, actual_eval)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

## Test Patient 2

revision patient

In [11]:
PATIENT_ID_2 = 2964021
patient_fixed_2 = ou.load_patient_data(patient_id=PATIENT_ID_2, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_2}")

Selected patient: 2964021

In [12]:
# Run all selected scenarios for Patient 2
all_results_2 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_2,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
        pso_ll_override=PSO_LL_OVERRIDE,
    )
    if result is None:
        continue
    all_results_2[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_2)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 8.01  |  Mech fail: 48.0%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 34.03  |  Mech fail: 48.0%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 23.91  |  Mech fail: 47.8%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 9.42  |  Mech fail: 47.1%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 9.42  |  Mech fail: 47.1%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 13.91  |  Mech fail: 50.3%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 27.79  |  Mech fail: 49.4%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 9.70  |  Mech fail: 47.1%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 9.42  |  Mech fail: 47.1%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [13]:
df_actual_2 = disp.display_actual_outcomes(
    PATIENT_ID_2, patient_fixed_2, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_2)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: PS
  num_levels_cat: lower
  num_interbody_fusion_levels: 2
  ALIF: 1
  XLIF: 0
  TLIF: 0
  num_rods: 3
  num_pelvic_screws: 3
  osteotomy (PSO): 0

  Mechanical Failure: No
  ODI: 15.0 (preop) → 0.0 (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 65.3%
  Predicted ODI (postop):        -1.2

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   27.01
    [mech_fail]            Minimize Mechanical Failure                 51.87
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        32.63
    [l4s1]                 Minimize L4S1 Penalty                       13.33
    [t4l1pa]               Minimize T4L1PA Penalty                     13.05
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        42.95
    [odi]                  Minimize Postop ODI                         13.05
    [gap_score]            Minimize GAP Score                          54.59
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   51.86
    [ll]                   Minimize LL (PI-LL) Penalty                 13.37

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     67.2           -1.3            65.9
1                    SS     32.7            5.9            38.6
2                  L4S1     51.8           -6.6            45.2
3            GlobalTilt     19.4          -16.7             2.7
4                  T4PA      6.6          -11.8            -5.2
5                  L1PA      1.7           -6.3            -4.6
6                    PI     54.9          -10.9            44.0
7                    PT     22.2          -16.8             5.4
8                   SVA      0.0          -10.1           -10.1
9                   Age       70              -               -
10            GAP Score      3.0              -             1.0
11         GAP Category       MD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)  -12.3 ⚠           -9.6         -21.9 ⚠
14   L1PA−ideal (|d|≤3)   -4.7 ⚠           -6.3         -11.0 ⚠
15         L4S1 (35–45)   51.8 ⚠           -6.6          45.2 ⚠
16    T4PA−L1PA (|d|≤3)    4.9 ⚠           -5.5          -0.6 ✓
17     LL−ideal (|d|≤3)   10.0 ⚠           -1.3           8.7 ⚠
18          GAP Cat (P)     MD ⚠              →             P ✓

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [14]:
# Build x vector for the actual surgical plan (Patient 2)
holdout_row_2 = holdout_df[holdout_df["id"] == PATIENT_ID_2].iloc[0]
actual_x_2 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_2[col]
    if var_spec.get("categorical", False):
        actual_x_2.append(var_spec["choices"].index(val))
    else:
        actual_x_2.append(int(val))
actual_x_2 = np.array(actual_x_2)

disp.display_patient_preop(patient_fixed_2, patient_id=PATIENT_ID_2)

# Evaluate actual plan using real postop values from holdout data
actual_eval_2 = ou.evaluate_actual_plan(
    actual_x_2, patient_fixed_2, holdout_row_2, mech_fail_bundle
)
disp.display_best_per_scenario(all_results_2, patient_fixed_2, actual_eval_2, SCENARIOS, deduplicate=DEDUP_BEST)

**Patient 2964021 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty,Minimize Postop ODI
0,Alignment Score,3.2,1.3,1.3,20.8,20.6,20.6,1.5,1.4,20.8,20.6
1,Optimization Score,3.2,8.0,34.1,23.9,9.4,9.4,13.9,27.8,9.9,9.6
2,Mech Fail Prob,65.3%,48.0%,48.1%,47.8%,47.1%,47.1%,50.3%,49.4%,47.9%,47.8%
3,Predicted ODI,0.0,-5.2,-7.5,-10.0,-12.5,-14.9,-8.0,-2.4,-12.4,-14.8
4,GAP Score,3.0 (MD) → 2 (P),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 1 (P),3.0 (MD) → 1 (P),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,,
7,UIV_implant,PS,Hook,Hook,FS,FS,FS,Hook,Hook,FS,FS
8,num_levels_cat,lower,higher,lower,higher,higher,lower,higher,higher,lower,lower
9,num_interbody_fusion_levels,2,0,0,1,0,0,2,1,1,0
10,ALIF,1,0,0,1,0,0,1,1,1,0
11,XLIF,0,0,0,0,0,0,1,0,0,0
12,TLIF,0,0,0,0,0,0,0,0,0,0
13,num_rods,3,4,4,4,4,4,4,4,4,4
14,num_pelvic_screws,3,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),0,1,1,1,1,1,1,0,1,0
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,,
18,LL,65.9,63.2,63.3,63.3,63.2,63.3,63.4,63.3,63.3,63.3
19,SS,38.6,34.5,34.4,33.7,33.9,33.8,34.7,34.6,33.7,33.8
20,L4S1,45.2,41.5,41.6,49.1,39.7,39.8,48.7,46.2,49.2,35.1
21,GlobalTilt,2.7,14.2,14.6,14.1,14.3,14.7,13.3,15.1,14.5,15.7
22,T4PA,-5.2,3.8,4.5,0.8,3.2,3.9,0.9,7.5,1.5,10.0
23,L1PA,-4.6,4.0,4.2,-0.1,3.0,3.2,0.2,5.0,0.1,7.4
24,SVA,-10.1,12.8,12.7,11.4,11.9,11.9,14.9,19.3,11.4,19.0
25,PI,54.9,54.9,54.9,54.9,54.9,54.9,54.9,54.9,54.9,54.9
26,PT,16.3,20.4,20.5,21.2,21.0,21.1,20.2,20.3,21.2,21.1
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,,
29,PI-LL (0–10),-11.0 ⚠,-8.3 ⚠,-8.4 ⚠,-8.4 ⚠,-8.3 ⚠,-8.4 ⚠,-8.5 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠
30,L1PA−ideal (|d|≤3),-11.0 ⚠,-2.5 ✓,-2.2 ✓,-6.5 ⚠,-3.4 ⚠,-3.2 ⚠,-6.3 ⚠,-1.4 ✓,-6.3 ⚠,1.0 ✓
31,L4S1 (35–45),45.2 ⚠,41.5 ✓,41.6 ✓,49.1 ⚠,39.7 ✓,39.8 ✓,48.7 ⚠,46.2 ⚠,49.2 ⚠,35.1 ✓
32,T4PA−L1PA (|d|≤3),-0.6 ✓,-0.2 ✓,0.3 ✓,0.9 ✓,0.2 ✓,0.7 ✓,0.8 ✓,2.5 ✓,1.4 ✓,2.6 ✓
33,LL−ideal (|d|≤3),8.7 ⚠,6.0 ⚠,6.1 ⚠,6.0 ⚠,6.0 ⚠,6.1 ⚠,6.2 ⚠,6.0 ⚠,6.1 ⚠,6.1 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,MD ⚠,MD ⚠,MD ⚠,P ✓,P ✓,MD ⚠,MD ⚠

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [15]:
# Evaluate actual plan once (real postop values don't change with weights)
actual_eval_2 = ou.evaluate_actual_plan(
    actual_x_2, patient_fixed_2, holdout_row_2, mech_fail_bundle
)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    if key not in all_results_2:
        continue
    r = all_results_2[key]
    preset = runs.PRESETS[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_2, actual_eval_2)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

## Test Patient 3

In [16]:
PATIENT_ID_3 = 818588
patient_fixed_3 = ou.load_patient_data(patient_id=PATIENT_ID_3, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_3}")

Selected patient: 818588

In [17]:
# Run all selected scenarios for Patient 3
all_results_3 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_3,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
        pso_ll_override=PSO_LL_OVERRIDE,
    )
    if result is None:
        continue
    all_results_3[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_3)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 10.57  |  Mech fail: 19.9%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 16.33  |  Mech fail: 19.4%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 9.70  |  Mech fail: 19.4%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 3.97  |  Mech fail: 19.9%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 3.97  |  Mech fail: 19.9%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 24.42  |  Mech fail: 19.4%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 21.93  |  Mech fail: 19.4%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 4.23  |  Mech fail: 20.0%

▶ Running: Minimize Postop ODI...
  ⚠ Skipped: patient has no preop ODI

============================================================
Completed 8 scenarios.

### Actual surgical plan/outcome

In [18]:
df_actual_3 = disp.display_actual_outcomes(
    PATIENT_ID_3, patient_fixed_3, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_3)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: PS
  num_levels_cat: lower
  num_interbody_fusion_levels: 1
  ALIF: 0
  XLIF: 0
  TLIF: 1
  num_rods: 3
  num_pelvic_screws: 2
  osteotomy (PSO): 0

  Mechanical Failure: Yes
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 27.8%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   11.98
    [mech_fail]            Minimize Mechanical Failure                 22.26
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        14.09
    [l4s1]                 Minimize L4S1 Penalty                        6.64
    [t4l1pa]               Minimize T4L1PA Penalty                      5.87
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        18.57
    [odi]                  Minimize Postop ODI                          5.56
    [gap_score]            Minimize GAP Score                          26.10
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   26.13
    [ll]                   Minimize LL (PI-LL) Penalty                  6.12

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     16.6           18.0            34.6
1                    SS     16.6              -               -
2                  L4S1     26.6            1.4            28.0
3            GlobalTilt     21.9           -9.6            12.3
4                  T4PA     14.0           -8.0             6.0
5                  L1PA      6.8           -5.0             1.8
6                    PI     38.2           -2.5            35.7
7                    PT     21.6           -5.6            16.0
8                   SVA     15.9          -15.9             0.0
9                   Age       78              -               -
10            GAP Score     12.0              -            10.0
11         GAP Category       SD              →              SD
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   21.6 ⚠          -20.5           1.1 ✓
14   L1PA−ideal (|d|≤3)    8.7 ⚠           -5.0           3.7 ⚠
15         L4S1 (35–45)   26.6 ⚠            1.4          28.0 ⚠
16    T4PA−L1PA (|d|≤3)    7.2 ⚠           -3.0           4.2 ⚠
17     LL−ideal (|d|≤3)  -31.6 ⚠           18.0         -13.6 ⚠
18          GAP Cat (P)     SD ⚠              →            SD ⚠

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [19]:
# Build x vector for the actual surgical plan (Patient 3)
holdout_row_3 = holdout_df[holdout_df["id"] == PATIENT_ID_3].iloc[0]
actual_x_3 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_3[col]
    if var_spec.get("categorical", False):
        actual_x_3.append(var_spec["choices"].index(val))
    else:
        actual_x_3.append(int(val))
actual_x_3 = np.array(actual_x_3)

disp.display_patient_preop(patient_fixed_3, patient_id=PATIENT_ID_3)

# Evaluate actual plan using real postop values from holdout data
actual_eval_3 = ou.evaluate_actual_plan(
    actual_x_3, patient_fixed_3, holdout_row_3, mech_fail_bundle
)
disp.display_best_per_scenario(all_results_3, patient_fixed_3, actual_eval_3, SCENARIOS, deduplicate=DEDUP_BEST)

**Patient 818588 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty
0,Alignment Score,13.8,9.0,9.2,9.2,12.8,9.4,9.9,9.9,9.0
1,Optimization Score,13.8,10.6,16.3,9.7,4.0,4.1,24.5,22.1,4.2
2,Mech Fail Prob,27.8%,19.9%,19.4%,19.4%,19.9%,20.4%,19.8%,19.8%,20.0%
3,Predicted ODI,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
4,GAP Score,12.0 (SD) → 6 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,
7,UIV_implant,PS,PS,FS,FS,FS,FS,FS,FS,Hook
8,num_levels_cat,lower,higher,higher,lower,higher,higher,higher,lower,higher
9,num_interbody_fusion_levels,1,0,0,0,1,1,0,0,0
10,ALIF,0,0,0,0,1,0,0,0,0
11,XLIF,0,0,0,0,0,1,0,0,0
12,TLIF,1,0,0,0,0,0,0,0,0
13,num_rods,3,4,4,4,4,4,4,4,4
14,num_pelvic_screws,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),0,1,1,1,1,1,0,0,1
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,
18,LL,34.6,41.4,41.8,41.6,42.1,41.8,41.8,41.6,42.5
19,SS,-,21.0,20.8,20.8,22.4,20.8,20.8,20.8,21.3
20,L4S1,28.0,31.8,28.9,29.0,38.3,26.7,24.2,24.3,30.7
21,GlobalTilt,12.3,8.5,8.7,8.8,8.3,8.7,9.6,9.8,8.5
22,T4PA,6.0,3.8,3.7,4.4,1.3,3.2,9.8,10.5,4.3
23,L1PA,1.8,1.0,1.9,2.1,-1.2,1.2,6.0,6.2,2.8
24,SVA,0.0,28.4,27.2,27.1,27.7,28.6,29.3,29.2,27.5
25,PI,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2
26,PT,-,17.2,17.4,17.4,15.8,17.4,17.4,17.4,16.9
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,
29,PI-LL (0–10),3.6 ✓,-3.2 ⚠,-3.6 ⚠,-3.4 ⚠,-3.9 ⚠,-3.6 ⚠,-3.6 ⚠,-3.4 ⚠,-4.3 ⚠
30,L1PA−ideal (|d|≤3),3.7 ⚠,2.9 ✓,3.8 ⚠,4.0 ⚠,0.7 ✓,3.1 ⚠,7.9 ⚠,8.1 ⚠,4.7 ⚠
31,L4S1 (35–45),28.0 ⚠,31.8 ⚠,28.9 ⚠,29.0 ⚠,38.3 ✓,26.7 ⚠,24.2 ⚠,24.3 ⚠,30.7 ⚠
32,T4PA−L1PA (|d|≤3),4.2 ⚠,2.8 ✓,1.8 ✓,2.3 ✓,2.5 ✓,2.0 ✓,3.8 ⚠,4.3 ⚠,1.5 ✓
33,LL−ideal (|d|≤3),-13.6 ⚠,-6.8 ⚠,-6.4 ⚠,-6.6 ⚠,-6.1 ⚠,-6.4 ⚠,-6.4 ⚠,-6.6 ⚠,-5.7 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [20]:
# Evaluate actual plan once (real postop values don't change with weights)
actual_eval_3 = ou.evaluate_actual_plan(
    actual_x_3, patient_fixed_3, holdout_row_3, mech_fail_bundle
)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    if key not in all_results_3:
        continue
    r = all_results_3[key]
    preset = runs.PRESETS[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_3, actual_eval_3)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

## Test Patient 4

In [21]:
PATIENT_ID_4 = 1176294
patient_fixed_4 = ou.load_patient_data(patient_id=PATIENT_ID_4, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_4}")

Selected patient: 1176294

In [22]:
# Run all selected scenarios for Patient 4
all_results_4 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_4,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
        pso_ll_override=PSO_LL_OVERRIDE,
    )
    if result is None:
        continue
    all_results_4[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_4)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 9.57  |  Mech fail: 55.7%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 35.83  |  Mech fail: 49.6%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 24.82  |  Mech fail: 49.6%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 10.08  |  Mech fail: 50.4%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 10.08  |  Mech fail: 50.4%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 14.96  |  Mech fail: 55.6%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 30.86  |  Mech fail: 55.6%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 12.90  |  Mech fail: 52.9%

▶ Running: Minimize Postop ODI...
  ⚠ Skipped: patient has no preop ODI

============================================================
Completed 8 scenarios.

### Actual surgical plan/outcome

In [23]:
df_actual_4 = disp.display_actual_outcomes(
    PATIENT_ID_4, patient_fixed_4, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_4)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: FS
  num_levels_cat: lower
  num_interbody_fusion_levels: 1
  ALIF: 1
  XLIF: 1
  TLIF: 0
  num_rods: 4
  num_pelvic_screws: 2
  osteotomy (PSO): 1

  Mechanical Failure: Yes
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 50.2%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   17.50
    [mech_fail]            Minimize Mechanical Failure                 38.78
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        25.12
    [l4s1]                 Minimize L4S1 Penalty                       10.05
    [t4l1pa]               Minimize T4L1PA Penalty                     10.05
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        31.14
    [odi]                  Minimize Postop ODI                         10.05
    [gap_score]            Minimize GAP Score                          38.28
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   43.51
    [ll]                   Minimize LL (PI-LL) Penalty                 13.08

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     22.7           43.2            65.9
1                    SS     17.3           18.3            35.6
2                  L4S1     15.8           18.1            33.9
3            GlobalTilt     40.3          -27.7            12.6
4                  T4PA     27.6          -23.3             4.3
5                  L1PA     18.7          -12.8             5.9
6                    PI     50.4           -0.7            49.7
7                    PT     33.1          -19.0            14.1
8                   SVA     83.6          -84.6            -1.0
9                   Age       71              -               -
10            GAP Score     10.0              -             1.0
11         GAP Category       SD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   27.7 ⚠          -43.9         -16.2 ⚠
14   L1PA−ideal (|d|≤3)   14.5 ⚠          -12.8           1.7 ✓
15         L4S1 (35–45)   15.8 ⚠           18.1          33.9 ⚠
16    T4PA−L1PA (|d|≤3)    8.9 ⚠          -10.5          -1.6 ✓
17     LL−ideal (|d|≤3)  -32.1 ⚠           43.2          11.1 ⚠
18          GAP Cat (P)     SD ⚠              →             P ✓

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [24]:
# Build x vector for the actual surgical plan (Patient 4)
holdout_row_4 = holdout_df[holdout_df["id"] == PATIENT_ID_4].iloc[0]
actual_x_4 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_4[col]
    if var_spec.get("categorical", False):
        actual_x_4.append(var_spec["choices"].index(val))
    else:
        actual_x_4.append(int(val))
actual_x_4 = np.array(actual_x_4)

disp.display_patient_preop(patient_fixed_4, patient_id=PATIENT_ID_4)

# Evaluate actual plan using real postop values from holdout data
actual_eval_4 = ou.evaluate_actual_plan(
    actual_x_4, patient_fixed_4, holdout_row_4, mech_fail_bundle
)
disp.display_best_per_scenario(all_results_4, patient_fixed_4, actual_eval_4, SCENARIOS, deduplicate=DEDUP_BEST)

**Patient 1176294 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty
0,Alignment Score,10.6,1.9,3.6,3.6,12.1,12.1,2.1,2.0,11.9
1,Optimization Score,10.6,9.6,35.8,24.8,10.1,10.1,15.0,30.9,12.9
2,Mech Fail Prob,50.2%,55.7%,49.6%,49.7%,50.4%,50.4%,55.6%,55.6%,52.9%
3,Predicted ODI,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
4,GAP Score,10.0 (SD) → 4 (MD),10.0 (SD) → 1 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 5 (MD),10.0 (SD) → 5 (MD),10.0 (SD) → 1 (P),10.0 (SD) → 1 (P),10.0 (SD) → 5 (MD)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,
7,UIV_implant,FS,Hook,FS,FS,FS,FS,Hook,Hook,Hook
8,num_levels_cat,lower,lower,higher,lower,higher,lower,higher,lower,lower
9,num_interbody_fusion_levels,1,3,0,0,1,1,3,3,2
10,ALIF,1,0,0,0,1,1,0,0,1
11,XLIF,1,1,0,0,0,0,1,1,1
12,TLIF,0,1,0,0,0,0,0,0,0
13,num_rods,4,4,4,4,4,4,4,4,4
14,num_pelvic_screws,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),1,1,1,1,1,1,1,1,1
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,
18,LL,65.9,42.9,41.0,41.3,41.7,42.0,42.7,42.9,43.3
19,SS,35.6,34.0,33.7,33.6,34.6,34.5,34.1,34.0,34.9
20,L4S1,33.9,32.0,28.8,28.9,38.2,38.2,29.4,29.5,37.8
21,GlobalTilt,12.6,19.2,19.6,19.7,19.5,19.6,19.1,19.2,19.3
22,T4PA,4.3,9.6,9.3,10.0,6.9,7.6,8.2,8.9,7.7
23,L1PA,5.9,7.9,8.7,8.9,5.6,5.8,8.7,8.9,6.0
24,SVA,-1.0,76.4,61.4,61.2,60.7,60.5,76.5,76.4,63.5
25,PI,50.4,50.4,50.4,50.4,50.4,50.4,50.4,50.4,50.4
26,PT,14.8,16.4,16.7,16.8,15.8,15.9,16.3,16.4,15.5
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,
29,PI-LL (0–10),-15.5 ⚠,7.5 ✓,9.4 ✓,9.1 ✓,8.7 ✓,8.4 ✓,7.7 ✓,7.5 ✓,7.1 ✓
30,L1PA−ideal (|d|≤3),1.7 ✓,3.7 ⚠,4.5 ⚠,4.7 ⚠,1.4 ✓,1.6 ✓,4.5 ⚠,4.7 ⚠,1.8 ✓
31,L4S1 (35–45),33.9 ⚠,32.0 ⚠,28.8 ⚠,28.9 ⚠,38.2 ✓,38.2 ✓,29.4 ⚠,29.5 ⚠,37.8 ✓
32,T4PA−L1PA (|d|≤3),-1.6 ✓,1.7 ✓,0.6 ✓,1.1 ✓,1.3 ✓,1.8 ✓,-0.5 ✓,0.0 ✓,1.7 ✓
33,LL−ideal (|d|≤3),11.1 ⚠,-11.9 ⚠,-13.8 ⚠,-13.5 ⚠,-13.1 ⚠,-12.8 ⚠,-12.1 ⚠,-11.9 ⚠,-11.5 ⚠
34,GAP Category (P),MD ⚠,P ✓,P ✓,P ✓,MD ⚠,MD ⚠,P ✓,P ✓,MD ⚠

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [25]:
# Evaluate actual plan once (real postop values don't change with weights)
actual_eval_4 = ou.evaluate_actual_plan(
    actual_x_4, patient_fixed_4, holdout_row_4, mech_fail_bundle
)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    if key not in all_results_4:
        continue
    r = all_results_4[key]
    preset = runs.PRESETS[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_4, actual_eval_4)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*