# Optimization

## Import Libraries

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

import importlib
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

from src import config
import src.optimization_utils as ou
import src.solutions as s
import src.display as disp
import src.runs as runs
from src.problem import SpineProblem

# Reload to pick up any changes
importlib.reload(ou)
importlib.reload(s)
importlib.reload(disp)
importlib.reload(runs)

pd.set_option('display.max_columns', None)

In [2]:
# =============================================================================
# GA Configuration — change these to control optimization
# =============================================================================
POP_SIZE  = 100   # GA population size
N_GEN     = 20    # Number of generations
SEED      = 42    # Random seed for reproducibility
TOP_N     = 4     # Number of diverse solutions to display
SCORE_TOL = 5     # Score window around best for diversity selection

## Load Models

In [3]:
# Load all models
model_configs = {
    "Mechanical Failure": config.MECH_FAIL_MODEL,
    "L4S1": config.L4S1_MODEL,
    "LL": config.LL_MODEL,
    "T4PA": config.T4PA_MODEL,
    "L1PA": config.L1PA_MODEL,
    "SVA": config.SVA_MODEL,
    "SS": config.SS_MODEL,
    "Global Tilt": config.GLOBAL_TILT_MODEL,
    "ODI": config.ODI_MODEL,
}

bundles = {name: ou.load_model_bundle(path) for name, path in model_configs.items()}

# Verify and display
print("Models loaded and verified:")
for name, bundle in bundles.items():
    status = "✓" if all(k in bundle for k in ["pipe", "features", "target"]) else "✗"
    print(f"  {status} {name}: {bundle.get('model_name', 'N/A')}")

# Extract individual bundles for use
mech_fail_bundle = bundles["Mechanical Failure"]
L4S1_bundle = bundles["L4S1"]
LL_bundle = bundles["LL"]
T4PA_bundle = bundles["T4PA"]
L1PA_bundle = bundles["L1PA"]
SVA_bundle = bundles["SVA"]
SS_bundle = bundles["SS"]
GT_bundle = bundles["Global Tilt"]
ODI_bundle = bundles["ODI"]

# Delta model bundles for postop predictions
delta_bundles = {
    "L4S1": L4S1_bundle,
    "LL": LL_bundle,
    "T4PA": T4PA_bundle,
    "L1PA": L1PA_bundle,
    "SS": SS_bundle,
    "GlobalTilt": GT_bundle,
    "SVA": SVA_bundle,
}

Models loaded and verified:
  ✓ Mechanical Failure: mech_fail_logreg
  ✓ L4S1: Ridge
  ✓ LL: RandomForest
  ✓ T4PA: Ridge
  ✓ L1PA: Ridge
  ✓ SVA: XGBRegressor
  ✓ SS: XGBRegressor
  ✓ Global Tilt: XGBRegressor
  ✓ ODI: Ridge

In [4]:
# ---- Check categories in training data vs each model ----
train_df = pd.read_csv(config.DATA_PROCESSED)
print("Training data:", config.DATA_PROCESSED)
print(f"  Shape: {train_df.shape}")
print(f"  ASA_CLASS unique: {sorted(train_df['ASA_CLASS'].dropna().unique())}")
print(f"  sex unique: {sorted(train_df['sex'].dropna().unique())}")
print(f"  UIV_implant unique: {sorted(train_df['UIV_implant'].dropna().unique())}")
print(f"  num_levels_cat unique: {sorted(train_df['num_levels_cat'].dropna().unique())}")

Training data: /Users/vanjaglisic/Documents/UW_MSDS/CAPSTONE/repo work/Data-Science-Capstone/data/processed/cleaned_for_modeling.csv
  Shape: (271, 109)
  ASA_CLASS unique: ['1', '2', '3', '4', '4E']
  sex unique: ['FEMALE', 'MALE']
  UIV_implant unique: ['FS', 'Hook', 'PS']
  num_levels_cat unique: ['higher', 'lower']

## Optimization Scenarios

Each scenario uses a different set of composite score weights to explore how the optimizer behaves under different objectives. Predefined presets are in `src/runs.py`. To add a new scenario, add a new entry to `runs.PRESETS` and include its key below.

In [5]:
# =============================================================================
# SELECT SCENARIOS TO RUN
# =============================================================================
# Available presets (defined in src/runs.py):
#   "equal"           - All 6 alignment components weighted equally
#   "mech_fail"       - Primarily mech failure, small alignment weights
#   "mech_fail_t4l1pa"- Mech failure + T4PA-L1PA mismatch
#   "l4s1"            - Primarily L4-S1 in ideal range
#   "t4l1pa"          - Primarily T4PA-L1PA mismatch
#   "equal_plus_mech" - Composite (equal) blended 50/50 with mech failure
#   "odi"             - Primarily lowest predicted postop ODI
#   "gap_score"       - Primarily GAP score + category improvement
#   "gap_score_mech_fail" - GAP score + Mechanical Failure
#   "ll"              - Primarily PI-LL mismatch
#
# To add a new scenario: add an entry to runs.PRESETS in src/runs.py,
# then include its key here.

SCENARIOS = ["equal", "mech_fail", "mech_fail_t4l1pa", "l4s1", "t4l1pa", "gap_score", "gap_score_mech_fail", "ll", "odi"]

# Show selected scenarios
for key in SCENARIOS:
    runs.print_preset(runs.PRESETS[key])

============================================================
  Equal Weights (Composite)
  All 6 alignment components and mechanical failure weighted equally
============================================================
                       GAP Score: 0.1429 ◀
                    L1PA penalty: 0.1429 ◀
                    L4S1 penalty: 0.1429 ◀
                  T4L1PA penalty: 0.1429 ◀
                      LL penalty: 0.1429 ◀
        GAP category improvement: 0.1429 ◀
         Mechanical failure prob: 0.1429 ◀

============================================================
  Minimize Mechanical Failure
  Primarily mechanical failure probability, with small alignment weights
============================================================
                       GAP Score: 0.0500 ◀
                    L1PA penalty: 0.0500 ◀
                    L4S1 penalty: 0.0500 ◀
                  T4L1PA penalty: 0.0500 ◀
                      LL penalty: 0.0500 ◀
        GAP category improvement: 0.0500 ◀
         Mechanical failure prob: 0.7000 ◀

============================================================
  Minimize Mechanical Failure + T4L1PA
  Mechanical failure probability and T4PA-L1PA mismatch weighted equally
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.5000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize L4S1 Penalty
  Primarily L4-S1 in ideal range (35-45°), with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.8000 ◀
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize T4L1PA Penalty
  Primarily T4PA-L1PA mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.8000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.5000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.3000 ◀
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score and Mechanical Failure
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.4000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.1000 ◀
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize LL (PI-LL) Penalty
  Primarily PI-LL mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.8000 ◀
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize Postop ODI
  Primarily lowest predicted postoperative ODI, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀
                      ODI postop: 0.8000 ◀

In [6]:
UIV_CHOICES, xl, xu = ou.get_decision_config()

print("UIV_CHOICES:", UIV_CHOICES)
print("xl:", xl)
print("xu:", xu)

# Use column names from config
print(pd.DataFrame([xl, xu], index=["xl","xu"], columns=config.DECISION_VAR_NAMES))

UIV_CHOICES: ['Hook', 'PS', 'FS']
xl: [0 0 0 0 0 0 1 2 0]
xu: [2 1 5 1 1 1 6 4 1]
    uiv_code  num_levels_cat_code  num_interbody_fusion_levels  ALIF  XLIF  \
xl         0                    0                            0     0     0
xu         2                    1                            5     1     1

    TLIF  num_rods  num_pelvic_screws  osteotomy
xl     0         1                  2          0
xu     1         6                  4          1

## Test Patient 1

In [7]:
# Show holdout patients summary
holdout_df = pd.read_csv(config.DATA_HOLDOUT)

summary_cols = [
    'sex', 'age', 'ASA_CLASS',
    "id", "description", "revision", "mech_fail_last",
    "gap_score_preop", "gap_category", "gap_score_postop", "gap_category_postop",
    "UIV_implant", "num_levels_cat", "num_interbody_fusion_levels",
    "ALIF", "XLIF", "TLIF", "num_rods", "num_pelvic_screws", "osteotomy",
    "ODI_preop"
]
display(holdout_df[summary_cols].set_index("id"))

# Select patient
PATIENT_ID = 6380632
patient_fixed = ou.load_patient_data(patient_id=PATIENT_ID, data_path=config.DATA_HOLDOUT)
print(f"\nSelected patient: {PATIENT_ID}")

,sex,age,ASA_CLASS,description,revision,mech_fail_last,gap_score_preop,gap_category,gap_score_postop,gap_category_postop,UIV_implant,num_levels_cat,num_interbody_fusion_levels,ALIF,XLIF,TLIF,num_rods,num_pelvic_screws,osteotomy,ODI_preop
id,,,,,,,,,,,,,,,,,,,,
818588,MALE,78,2.0,mech failure - small GAP improvement;,0,1.0,12.0,SD,10.0,SD,PS,lower,1,0,0,1,3,2,0,NaN
1176294,MALE,71,NaN,mech failure - large GAP improvement;,1,1.0,10.0,SD,1.0,P,FS,lower,1,1,1,0,4,2,1,NaN
2964021,FEMALE,70,3.0,revision - GAP improvement 3 to 1,0,0.0,3.0,MD,1.0,P,PS,lower,2,1,0,0,3,3,0,15.0
6380632,FEMALE,76,3.0,large GAP imporovement,0,0.0,12.0,SD,1.0,P,Hook,higher,2,1,0,0,3,2,0,NaN

Selected patient: 6380632

**Run GA for all scenarios**

For each selected scenario, runs the GA optimizer and collects results. 

**Constraints (all scenarios):** 
- If `num_interbody_fusion_levels = 0`, then `ALIF = XLIF = TLIF = 0`.
- `num_interbody_fusion_levels` must be ≥ the sum of selected fusion types (`ALIF + XLIF + TLIF`).

In [8]:
all_results = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
    )
    all_results[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 7.25  |  Mech fail: 42.7%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 29.60  |  Mech fail: 41.7%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 17.37  |  Mech fail: 34.7%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 8.66  |  Mech fail: 43.3%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 8.68  |  Mech fail: 43.3%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 12.51  |  Mech fail: 43.3%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 24.42  |  Mech fail: 42.7%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 8.98  |  Mech fail: 43.3%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 6.95  |  Mech fail: 34.7%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [9]:
df_actual = disp.display_actual_outcomes(
    PATIENT_ID, patient_fixed, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: Hook
  num_levels_cat: higher
  num_interbody_fusion_levels: 2
  ALIF: 1
  XLIF: 0
  TLIF: 0
  num_rods: 3
  num_pelvic_screws: 2
  osteotomy (PSO): 0

  Mechanical Failure: No
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 63.1%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   17.72
    [mech_fail]            Minimize Mechanical Failure                 47.19
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        31.53
    [l4s1]                 Minimize L4S1 Penalty                       12.61
    [t4l1pa]               Minimize T4L1PA Penalty                     12.61
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        36.61
    [odi]                  Minimize Postop ODI                         12.61
    [gap_score]            Minimize GAP Score                          37.00
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   46.84
    [ll]                   Minimize LL (PI-LL) Penalty                 12.77

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     30.4           32.5            62.9
1                    SS     33.8           11.5            45.3
2                  L4S1     34.5            7.0            41.5
3            GlobalTilt     42.2          -23.9            18.3
4                  T4PA     24.8          -15.2             9.6
5                  L1PA     12.2           -4.8             7.4
6                    PI     58.6            2.2            60.8
7                    PT     24.8           -9.3            15.5
8                   SVA    154.6         -124.8            29.8
9                   Age       76              -               -
10            GAP Score     12.0              -             1.0
11         GAP Category       SD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   28.2 ⚠          -30.3          -2.1 ⚠
14   L1PA−ideal (|d|≤3)    3.9 ⚠           -4.8          -0.9 ✓
15         L4S1 (35–45)   34.5 ⚠            7.0          41.5 ✓
16    T4PA−L1PA (|d|≤3)   12.6 ⚠          -10.4           2.2 ✓
17     LL−ideal (|d|≤3)  -28.8 ⚠           32.5           3.7 ⚠
18          GAP Cat (P)     SD ⚠              →             P ✓

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [10]:
# Build x vector for the actual surgical plan (from holdout data)
holdout_row = holdout_df[holdout_df["id"] == PATIENT_ID].iloc[0]
actual_x = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row[col]
    if var_spec.get("categorical", False):
        actual_x.append(var_spec["choices"].index(val))
    else:
        actual_x.append(int(val))
actual_x = np.array(actual_x)

disp.display_patient_preop(patient_fixed, patient_id=PATIENT_ID)

# Evaluate actual plan with equal weights for a neutral baseline
actual_eval = ou.evaluate_solution(
    actual_x, patient_fixed, delta_bundles, mech_fail_bundle,
    weights=runs.PRESETS["equal"]["weights"], odi_bundle=ODI_bundle
)
disp.display_best_per_scenario(all_results, patient_fixed, actual_eval, SCENARIOS)

**Patient 6380632 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty,Minimize Postop ODI
0,Alignment Score,10.2,1.3,1.4,1.3,1.4,1.4,1.4,1.3,1.4,1.3
1,Optimization Score,17.7,7.3,29.6,17.4,8.7,8.7,12.5,24.4,9.0,6.9
2,Mech Fail Prob,63.1%,42.7%,41.7%,34.7%,43.3%,43.3%,43.3%,42.7%,43.3%,34.7%
3,Predicted ODI,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,,
7,UIV_implant,Hook,FS,FS,FS,PS,PS,PS,FS,PS,FS
8,num_levels_cat,higher,lower,lower,lower,lower,lower,lower,lower,lower,lower
9,num_interbody_fusion_levels,2,0,0,0,0,0,0,0,0,0
10,ALIF,1,0,0,0,0,0,0,0,0,0
11,XLIF,0,0,0,0,0,0,0,0,0,0
12,TLIF,0,0,0,0,0,0,0,0,0,0
13,num_rods,3,5,5,6,5,5,5,5,5,6
14,num_pelvic_screws,2,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),0,0,1,0,0,0,0,0,0,0
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,,
18,LL,54.0,53.2,53.2,53.2,53.1,53.1,53.1,53.2,53.1,53.2
19,SS,45.0,42.9,42.9,42.9,42.9,42.9,42.9,42.9,42.9,42.9
20,L4S1,45.0,36.4,40.1,37.7,39.3,39.3,39.3,36.4,39.3,37.7
21,GlobalTilt,22.1,22.7,21.1,22.7,22.7,22.7,22.7,22.7,22.7,22.7
22,T4PA,6.9,9.6,3.3,9.5,9.6,9.6,9.6,9.6,9.6,9.5
23,L1PA,5.2,6.7,2.5,6.3,5.8,5.8,5.8,6.7,5.8,6.3
24,SVA,94.7,101.6,90.2,98.1,94.5,94.5,94.5,101.6,94.5,98.1
25,PI,58.6,58.6,58.6,58.6,58.6,58.6,58.6,58.6,58.6,58.6
26,PT,13.6,15.7,15.7,15.7,15.7,15.7,15.7,15.7,15.7,15.7
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,,
29,PI-LL (0–10),4.6 ✓,5.4 ✓,5.4 ✓,5.4 ✓,5.5 ✓,5.5 ✓,5.5 ✓,5.4 ✓,5.5 ✓,5.4 ✓
30,L1PA−ideal (|d|≤3),-3.1 ⚠,-1.6 ✓,-5.8 ⚠,-2.0 ✓,-2.5 ✓,-2.5 ✓,-2.5 ✓,-1.6 ✓,-2.5 ✓,-2.0 ✓
31,L4S1 (35–45),45.0 ✓,36.4 ✓,40.1 ✓,37.7 ✓,39.3 ✓,39.3 ✓,39.3 ✓,36.4 ✓,39.3 ✓,37.7 ✓
32,T4PA−L1PA (|d|≤3),1.7 ✓,2.8 ✓,0.8 ✓,3.2 ⚠,3.8 ⚠,3.8 ⚠,3.8 ⚠,2.8 ✓,3.8 ⚠,3.2 ⚠
33,LL−ideal (|d|≤3),-5.3 ⚠,-6.1 ⚠,-6.0 ⚠,-6.1 ⚠,-6.2 ⚠,-6.2 ⚠,-6.2 ⚠,-6.1 ⚠,-6.2 ⚠,-6.1 ⚠
34,GAP Category (P),MD ⚠,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [11]:
# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval = ou.evaluate_solution(
        actual_x, patient_fixed, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed, actual_eval)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

## Test Patient 2

revision patient

In [12]:
PATIENT_ID_2 = 2964021
patient_fixed_2 = ou.load_patient_data(patient_id=PATIENT_ID_2, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_2}")

Selected patient: 2964021

In [13]:
# Run all selected scenarios for Patient 2
all_results_2 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_2,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
    )
    all_results_2[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_2)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 23.34  |  Mech fail: 39.9%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 34.12  |  Mech fail: 39.9%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 15.87  |  Mech fail: 31.7%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 8.01  |  Mech fail: 40.0%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 6.49  |  Mech fail: 32.3%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 49.35  |  Mech fail: 39.0%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 38.45  |  Mech fail: 38.4%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 6.74  |  Mech fail: 32.2%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 6.28  |  Mech fail: 31.4%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [14]:
df_actual_2 = disp.display_actual_outcomes(
    PATIENT_ID_2, patient_fixed_2, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_2)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: PS
  num_levels_cat: lower
  num_interbody_fusion_levels: 2
  ALIF: 1
  XLIF: 0
  TLIF: 0
  num_rods: 3
  num_pelvic_screws: 3
  osteotomy (PSO): 0

  Mechanical Failure: No
  ODI: 15.0 (preop) → 0.0 (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 65.6%
  Predicted ODI (postop):        -2.0

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   27.06
    [mech_fail]            Minimize Mechanical Failure                 52.09
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        32.78
    [l4s1]                 Minimize L4S1 Penalty                       13.39
    [t4l1pa]               Minimize T4L1PA Penalty                     13.11
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        43.10
    [odi]                  Minimize Postop ODI                         13.11
    [gap_score]            Minimize GAP Score                          54.65
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   52.01
    [ll]                   Minimize LL (PI-LL) Penalty                 13.44

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     67.2           -1.3            65.9
1                    SS     32.7            5.9            38.6
2                  L4S1     51.8           -6.6            45.2
3            GlobalTilt     19.4          -16.7             2.7
4                  T4PA      6.6          -11.8            -5.2
5                  L1PA      1.7           -6.3            -4.6
6                    PI     54.9          -10.9            44.0
7                    PT     22.2          -16.8             5.4
8                   SVA      0.0          -10.1           -10.1
9                   Age       70              -               -
10            GAP Score      3.0              -             1.0
11         GAP Category       MD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)  -12.3 ⚠           -9.6         -21.9 ⚠
14   L1PA−ideal (|d|≤3)   -4.7 ⚠           -6.3         -11.0 ⚠
15         L4S1 (35–45)   51.8 ⚠           -6.6          45.2 ⚠
16    T4PA−L1PA (|d|≤3)    4.9 ⚠           -5.5          -0.6 ✓
17     LL−ideal (|d|≤3)   10.0 ⚠           -1.3           8.7 ⚠
18          GAP Cat (P)     MD ⚠              →             P ✓

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [15]:
# Build x vector for the actual surgical plan (Patient 2)
holdout_row_2 = holdout_df[holdout_df["id"] == PATIENT_ID_2].iloc[0]
actual_x_2 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_2[col]
    if var_spec.get("categorical", False):
        actual_x_2.append(var_spec["choices"].index(val))
    else:
        actual_x_2.append(int(val))
actual_x_2 = np.array(actual_x_2)

disp.display_patient_preop(patient_fixed_2, patient_id=PATIENT_ID_2)

# Evaluate actual plan with equal weights for a neutral baseline
actual_eval_2 = ou.evaluate_solution(
    actual_x_2, patient_fixed_2, delta_bundles, mech_fail_bundle,
    weights=runs.PRESETS["equal"]["weights"], odi_bundle=ODI_bundle
)
disp.display_best_per_scenario(all_results_2, patient_fixed_2, actual_eval_2, SCENARIOS)

**Patient 2964021 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty,Minimize Postop ODI
0,Alignment Score,20.6,20.6,20.6,20.6,20.6,20.6,20.6,20.6,20.6,20.6
1,Optimization Score,27.1,23.3,34.1,15.9,8.0,6.5,49.3,38.4,6.7,6.3
2,Mech Fail Prob,65.6%,39.9%,39.9%,31.7%,40.0%,32.3%,39.0%,38.4%,32.2%,31.4%
3,Predicted ODI,-2.0,-1.3,-1.3,-13.2,-4.5,-5.1,-4.6,-12.7,-1.9,-5.2
4,GAP Score,3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD),3.0 (MD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,,
7,UIV_implant,PS,PS,PS,FS,PS,PS,PS,FS,PS,PS
8,num_levels_cat,lower,higher,higher,lower,lower,lower,lower,lower,higher,lower
9,num_interbody_fusion_levels,2,0,0,0,0,0,0,0,0,0
10,ALIF,1,0,0,0,0,0,0,0,0,0
11,XLIF,0,0,0,0,0,0,0,0,0,0
12,TLIF,0,0,0,0,0,0,0,0,0,0
13,num_rods,3,5,5,6,5,6,5,5,6,6
14,num_pelvic_screws,3,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),0,0,0,0,0,0,1,1,0,1
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,,
18,LL,63.5,63.3,63.3,63.3,63.3,63.3,63.3,63.3,63.3,63.3
19,SS,33.2,33.5,33.5,33.5,33.5,33.5,33.5,33.5,33.5,33.5
20,L4S1,47.9,39.8,39.8,38.4,40.0,41.3,43.6,40.7,41.1,44.9
21,GlobalTilt,15.7,16.3,16.3,16.9,16.7,16.7,15.9,16.1,16.3,15.9
22,T4PA,6.3,9.0,9.0,9.6,9.7,9.7,3.4,3.4,8.9,3.4
23,L1PA,3.1,5.8,5.8,6.6,6.0,5.6,1.8,2.7,5.4,1.4
24,SVA,15.4,19.6,19.6,8.5,20.5,8.5,7.3,7.4,7.6,-4.7
25,PI,54.9,54.9,54.9,54.9,54.9,54.9,54.9,54.9,54.9,54.9
26,PT,21.7,21.4,21.4,21.4,21.4,21.4,21.4,21.4,21.4,21.4
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,,
29,PI-LL (0–10),-8.6 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠,-8.4 ⚠
30,L1PA−ideal (|d|≤3),-3.4 ⚠,-0.6 ✓,-0.6 ✓,0.1 ✓,-0.4 ✓,-0.8 ✓,-4.7 ⚠,-3.7 ⚠,-1.0 ✓,-5.1 ⚠
31,L4S1 (35–45),47.9 ⚠,39.8 ✓,39.8 ✓,38.4 ✓,40.0 ✓,41.3 ✓,43.6 ✓,40.7 ✓,41.1 ✓,44.9 ✓
32,T4PA−L1PA (|d|≤3),3.2 ⚠,3.2 ⚠,3.2 ⚠,3.0 ⚠,3.7 ⚠,4.0 ⚠,1.7 ✓,0.7 ✓,3.5 ⚠,2.0 ✓
33,LL−ideal (|d|≤3),6.2 ⚠,6.0 ⚠,6.0 ⚠,6.1 ⚠,6.1 ⚠,6.1 ⚠,6.1 ⚠,6.1 ⚠,6.0 ⚠,6.1 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [16]:
# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results_2[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval_2 = ou.evaluate_solution(
        actual_x_2, patient_fixed_2, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_2, actual_eval_2)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

## Test Patient 3

In [17]:
PATIENT_ID_3 = 818588
patient_fixed_3 = ou.load_patient_data(patient_id=PATIENT_ID_3, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_3}")

Selected patient: 818588

In [18]:
# Run all selected scenarios for Patient 3
all_results_3 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_3,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
    )
    all_results_3[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_3)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 10.25  |  Mech fail: 15.2%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 10.56  |  Mech fail: 11.1%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 7.44  |  Mech fail: 14.8%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 3.98  |  Mech fail: 15.1%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 2.92  |  Mech fail: 14.6%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 23.57  |  Mech fail: 15.1%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 19.80  |  Mech fail: 15.1%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 3.33  |  Mech fail: 15.2%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 2.21  |  Mech fail: 11.1%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [19]:
df_actual_3 = disp.display_actual_outcomes(
    PATIENT_ID_3, patient_fixed_3, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_3)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: PS
  num_levels_cat: lower
  num_interbody_fusion_levels: 1
  ALIF: 0
  XLIF: 0
  TLIF: 1
  num_rods: 3
  num_pelvic_screws: 2
  osteotomy (PSO): 0

  Mechanical Failure: Yes
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 27.1%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   11.80
    [mech_fail]            Minimize Mechanical Failure                 21.73
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        13.68
    [l4s1]                 Minimize L4S1 Penalty                        6.15
    [t4l1pa]               Minimize T4L1PA Penalty                      5.65
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        18.16
    [odi]                  Minimize Postop ODI                          5.41
    [gap_score]            Minimize GAP Score                          25.95
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   25.77
    [ll]                   Minimize LL (PI-LL) Penalty                  5.98

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     16.6           18.0            34.6
1                    SS     16.6              -               -
2                  L4S1     26.6            1.4            28.0
3            GlobalTilt     21.9           -9.6            12.3
4                  T4PA     14.0           -8.0             6.0
5                  L1PA      6.8           -5.0             1.8
6                    PI     38.2           -2.5            35.7
7                    PT     21.6           -5.6            16.0
8                   SVA     15.9          -15.9             0.0
9                   Age       78              -               -
10            GAP Score     12.0              -            10.0
11         GAP Category       SD              →              SD
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   21.6 ⚠          -20.5           1.1 ✓
14   L1PA−ideal (|d|≤3)    8.7 ⚠           -5.0           3.7 ⚠
15         L4S1 (35–45)   26.6 ⚠            1.4          28.0 ⚠
16    T4PA−L1PA (|d|≤3)    7.2 ⚠           -3.0           4.2 ⚠
17     LL−ideal (|d|≤3)  -31.6 ⚠           18.0         -13.6 ⚠
18          GAP Cat (P)     SD ⚠              →            SD ⚠

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [20]:
# Build x vector for the actual surgical plan (Patient 3)
holdout_row_3 = holdout_df[holdout_df["id"] == PATIENT_ID_3].iloc[0]
actual_x_3 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_3[col]
    if var_spec.get("categorical", False):
        actual_x_3.append(var_spec["choices"].index(val))
    else:
        actual_x_3.append(int(val))
actual_x_3 = np.array(actual_x_3)

disp.display_patient_preop(patient_fixed_3, patient_id=PATIENT_ID_3)

# Evaluate actual plan with equal weights for a neutral baseline
actual_eval_3 = ou.evaluate_solution(
    actual_x_3, patient_fixed_3, delta_bundles, mech_fail_bundle,
    weights=runs.PRESETS["equal"]["weights"], odi_bundle=ODI_bundle
)
disp.display_best_per_scenario(all_results_3, patient_fixed_3, actual_eval_3, SCENARIOS)

**Patient 818588 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty,Minimize Postop ODI
0,Alignment Score,9.3,9.4,9.4,9.6,9.3,12.8,9.3,9.3,9.4,9.4
1,Optimization Score,11.8,10.3,10.6,7.4,4.0,2.9,23.6,19.8,3.3,2.2
2,Mech Fail Prob,27.1%,15.2%,11.1%,14.8%,15.1%,14.6%,15.1%,15.1%,15.2%,11.1%
3,Predicted ODI,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
4,GAP Score,12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 6 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD),12.0 (SD) → 3 (MD)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,,
7,UIV_implant,PS,Hook,FS,FS,PS,PS,PS,PS,Hook,FS
8,num_levels_cat,lower,lower,lower,lower,lower,lower,lower,lower,lower,lower
9,num_interbody_fusion_levels,1,0,0,0,0,0,0,0,0,0
10,ALIF,0,0,0,0,0,0,0,0,0,0
11,XLIF,0,0,0,0,0,0,0,0,0,0
12,TLIF,1,0,0,0,0,0,0,0,0,0
13,num_rods,3,5,6,5,5,5,5,5,5,6
14,num_pelvic_screws,2,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),0,0,0,0,0,1,0,0,0,0
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,,
18,LL,41.0,42.3,41.6,41.6,41.1,41.2,41.1,41.1,42.3,41.6
19,SS,21.2,21.9,20.9,20.9,21.1,21.1,21.1,21.1,21.9,20.9
20,L4S1,30.2,28.4,27.9,26.7,29.5,33.2,29.5,29.5,28.4,27.9
21,GlobalTilt,10.8,10.3,10.5,10.5,10.5,9.8,10.5,10.5,10.3,10.5
22,T4PA,10.4,10.8,10.1,10.1,10.2,3.9,10.2,10.2,10.8,10.1
23,L1PA,4.7,6.9,5.5,5.9,5.0,0.7,5.0,5.0,6.9,5.5
24,SVA,26.5,27.6,15.1,28.9,28.9,24.2,28.9,28.9,27.6,15.1
25,PI,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2,38.2
26,PT,17.0,16.3,17.3,17.3,17.1,17.1,17.1,17.1,16.3,17.3
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,,
29,PI-LL (0–10),-2.8 ⚠,-4.1 ⚠,-3.4 ⚠,-3.4 ⚠,-2.9 ⚠,-3.0 ⚠,-2.9 ⚠,-2.9 ⚠,-4.1 ⚠,-3.4 ⚠
30,L1PA−ideal (|d|≤3),6.6 ⚠,8.8 ⚠,7.4 ⚠,7.8 ⚠,6.9 ⚠,2.6 ✓,6.9 ⚠,6.9 ⚠,8.8 ⚠,7.4 ⚠
31,L4S1 (35–45),30.2 ⚠,28.4 ⚠,27.9 ⚠,26.7 ⚠,29.5 ⚠,33.2 ⚠,29.5 ⚠,29.5 ⚠,28.4 ⚠,27.9 ⚠
32,T4PA−L1PA (|d|≤3),5.7 ⚠,3.9 ⚠,4.6 ⚠,4.2 ⚠,5.2 ⚠,3.2 ⚠,5.2 ⚠,5.2 ⚠,3.9 ⚠,4.6 ⚠
33,LL−ideal (|d|≤3),-7.2 ⚠,-6.0 ⚠,-6.7 ⚠,-6.7 ⚠,-7.1 ⚠,-7.1 ⚠,-7.1 ⚠,-7.1 ⚠,-6.0 ⚠,-6.7 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠,MD ⚠

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [21]:
# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results_3[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval_3 = ou.evaluate_solution(
        actual_x_3, patient_fixed_3, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_3, actual_eval_3)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

## Test Patient 4

In [22]:
PATIENT_ID_4 = 1176294
patient_fixed_4 = ou.load_patient_data(patient_id=PATIENT_ID_4, data_path=config.DATA_HOLDOUT)
print(f"Selected patient: {PATIENT_ID_4}")

Selected patient: 1176294

In [23]:
# Run all selected scenarios for Patient 4
all_results_4 = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed_4,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=POP_SIZE,
        n_gen=N_GEN,
        seed=SEED,
        verbose=False,
        top_n=TOP_N,
        score_tolerance=SCORE_TOL,
    )
    all_results_4[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results_4)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 9.36  |  Mech fail: 42.7%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 25.22  |  Mech fail: 34.5%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 21.31  |  Mech fail: 42.5%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 8.51  |  Mech fail: 41.4%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 8.58  |  Mech fail: 42.5%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 14.48  |  Mech fail: 33.9%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 23.08  |  Mech fail: 33.8%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 10.40  |  Mech fail: 36.1%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 6.80  |  Mech fail: 34.0%

============================================================
Completed 9 scenarios.

### Actual surgical plan/outcome

In [24]:
df_actual_4 = disp.display_actual_outcomes(
    PATIENT_ID_4, patient_fixed_4, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual_4)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: FS
  num_levels_cat: lower
  num_interbody_fusion_levels: 1
  ALIF: 1
  XLIF: 1
  TLIF: 0
  num_rods: 4
  num_pelvic_screws: 2
  osteotomy (PSO): 1

  Mechanical Failure: Yes
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 50.9%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   17.58
    [mech_fail]            Minimize Mechanical Failure                 39.21
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        25.43
    [l4s1]                 Minimize L4S1 Penalty                       10.17
    [t4l1pa]               Minimize T4L1PA Penalty                     10.17
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        31.44
    [odi]                  Minimize Postop ODI                         10.17
    [gap_score]            Minimize GAP Score                          38.40
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   43.81
    [ll]                   Minimize LL (PI-LL) Penalty                 13.17

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     22.7           43.2            65.9
1                    SS     17.3           18.3            35.6
2                  L4S1     15.8           18.1            33.9
3            GlobalTilt     40.3          -27.7            12.6
4                  T4PA     27.6          -23.3             4.3
5                  L1PA     18.7          -12.8             5.9
6                    PI     50.4           -0.7            49.7
7                    PT     33.1          -19.0            14.1
8                   SVA     83.6          -84.6            -1.0
9                   Age       71              -               -
10            GAP Score     10.0              -             1.0
11         GAP Category       SD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   27.7 ⚠          -43.9         -16.2 ⚠
14   L1PA−ideal (|d|≤3)   14.5 ⚠          -12.8           1.7 ✓
15         L4S1 (35–45)   15.8 ⚠           18.1          33.9 ⚠
16    T4PA−L1PA (|d|≤3)    8.9 ⚠          -10.5          -1.6 ✓
17     LL−ideal (|d|≤3)  -32.1 ⚠           43.2          11.1 ⚠
18          GAP Cat (P)     SD ⚠              →             P ✓

### Best Solution per Scenario

A single table comparing the **Actual** surgical plan against the **best** optimized solution from each scenario.

In [25]:
# Build x vector for the actual surgical plan (Patient 4)
holdout_row_4 = holdout_df[holdout_df["id"] == PATIENT_ID_4].iloc[0]
actual_x_4 = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row_4[col]
    if var_spec.get("categorical", False):
        actual_x_4.append(var_spec["choices"].index(val))
    else:
        actual_x_4.append(int(val))
actual_x_4 = np.array(actual_x_4)

disp.display_patient_preop(patient_fixed_4, patient_id=PATIENT_ID_4)

# Evaluate actual plan with equal weights for a neutral baseline
actual_eval_4 = ou.evaluate_solution(
    actual_x_4, patient_fixed_4, delta_bundles, mech_fail_bundle,
    weights=runs.PRESETS["equal"]["weights"], odi_bundle=ODI_bundle
)
disp.display_best_per_scenario(all_results_4, patient_fixed_4, actual_eval_4, SCENARIOS)

**Patient 1176294 — Preop Profile**

,Parameter,Actual,Equal Weights (Composite),Minimize Mechanical Failure,Minimize Mechanical Failure + T4L1PA,Minimize L4S1 Penalty,Minimize T4L1PA Penalty,Minimize GAP Score,Minimize GAP Score and Mechanical Failure,Minimize LL (PI-LL) Penalty,Minimize Postop ODI
0,Alignment Score,12.0,3.8,3.6,3.7,3.4,3.7,3.9,4.1,3.6,3.8
1,Optimization Score,17.6,9.4,25.2,21.3,8.5,8.6,14.5,23.1,10.4,6.8
2,Mech Fail Prob,50.9%,42.7%,34.5%,42.5%,41.4%,42.5%,33.9%,33.8%,36.1%,34.0%
3,Predicted ODI,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
4,GAP Score,10.0 (SD) → 5 (MD),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P),10.0 (SD) → 2 (P)
5,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,,,,,,,
7,UIV_implant,FS,Hook,PS,PS,PS,PS,FS,FS,Hook,FS
8,num_levels_cat,lower,lower,higher,lower,higher,lower,higher,higher,lower,lower
9,num_interbody_fusion_levels,1,0,0,0,0,0,0,0,1,0
10,ALIF,1,0,0,0,0,0,0,0,0,0
11,XLIF,1,0,0,0,0,0,0,1,0,0
12,TLIF,0,0,0,0,0,0,0,0,0,0
13,num_rods,4,5,6,5,5,5,6,6,6,6
14,num_pelvic_screws,2,2,2,2,2,2,2,2,2,2
15,osteotomy (PSO),1,0,0,0,1,0,0,0,0,0
16,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,,,,,,,
18,LL,42.1,41.8,41.0,41.3,41.1,41.3,41.0,41.1,41.8,41.3
19,SS,33.0,33.0,33.0,32.8,33.0,32.8,32.8,32.6,33.0,32.6
20,L4S1,35.5,27.8,29.9,28.9,32.3,28.9,27.1,24.9,29.3,27.3
21,GlobalTilt,21.6,22.7,22.6,22.9,20.9,22.9,23.3,23.3,22.8,23.6
22,T4PA,7.0,16.2,14.8,15.6,8.6,15.6,14.7,14.7,15.7,15.4
23,L1PA,4.8,13.0,10.5,11.1,6.6,11.1,11.4,11.1,12.4,11.6
24,SVA,68.9,61.9,55.0,63.1,60.5,63.1,59.1,64.6,53.4,58.7
25,PI,50.4,50.4,50.4,50.4,50.4,50.4,50.4,50.4,50.4,50.4
26,PT,17.4,17.4,17.4,17.6,17.4,17.6,17.6,17.8,17.4,17.8
27,────────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,,,,,,,
29,PI-LL (0–10),8.3 ✓,8.6 ✓,9.4 ✓,9.1 ✓,9.3 ✓,9.1 ✓,9.4 ✓,9.3 ✓,8.6 ✓,9.1 ✓
30,L1PA−ideal (|d|≤3),0.6 ✓,8.8 ⚠,6.3 ⚠,6.9 ⚠,2.4 ✓,6.9 ⚠,7.2 ⚠,6.9 ⚠,8.2 ⚠,7.4 ⚠
31,L4S1 (35–45),35.5 ✓,27.8 ⚠,29.9 ⚠,28.9 ⚠,32.3 ⚠,28.9 ⚠,27.1 ⚠,24.9 ⚠,29.3 ⚠,27.3 ⚠
32,T4PA−L1PA (|d|≤3),2.2 ✓,3.2 ⚠,4.3 ⚠,4.5 ⚠,2.0 ✓,4.5 ⚠,3.3 ⚠,3.7 ⚠,3.3 ⚠,3.8 ⚠
33,LL−ideal (|d|≤3),-12.7 ⚠,-13.0 ⚠,-13.8 ⚠,-13.5 ⚠,-13.8 ⚠,-13.5 ⚠,-13.8 ⚠,-13.8 ⚠,-13.0 ⚠,-13.5 ⚠
34,GAP Category (P),MD ⚠,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓,P ✓

### 4 Best Solutions per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [26]:
# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results_4[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval_4 = ou.evaluate_solution(
        actual_x_4, patient_fixed_4, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed_4, actual_eval_4)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*