# Optimization

## Import Libraries

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

import importlib
import numpy as np
import pandas as pd

from src import config
import src.optimization_utils as ou
import src.solutions as s
import src.display as disp
import src.runs as runs
from src.problem import SpineProblem

# Reload to pick up any changes
importlib.reload(ou)
importlib.reload(s)
importlib.reload(disp)
importlib.reload(runs)

pd.set_option('display.max_columns', None)

## Load Models

In [2]:
# Load all models
model_configs = {
    "Mechanical Failure": config.MECH_FAIL_MODEL,
    "L4S1": config.L4S1_MODEL,
    "LL": config.LL_MODEL,
    "T4PA": config.T4PA_MODEL,
    "L1PA": config.L1PA_MODEL,
    "SVA": config.SVA_MODEL,
    "SS": config.SS_MODEL,
    "Global Tilt": config.GLOBAL_TILT_MODEL,
    "ODI": config.ODI_MODEL,
}

bundles = {name: ou.load_model_bundle(path) for name, path in model_configs.items()}

# Verify and display
print("Models loaded and verified:")
for name, bundle in bundles.items():
    status = "✓" if all(k in bundle for k in ["pipe", "features", "target"]) else "✗"
    print(f"  {status} {name}: {bundle.get('model_name', 'N/A')}")

# Extract individual bundles for use
mech_fail_bundle = bundles["Mechanical Failure"]
L4S1_bundle = bundles["L4S1"]
LL_bundle = bundles["LL"]
T4PA_bundle = bundles["T4PA"]
L1PA_bundle = bundles["L1PA"]
SVA_bundle = bundles["SVA"]
SS_bundle = bundles["SS"]
GT_bundle = bundles["Global Tilt"]
ODI_bundle = bundles["ODI"]

# Delta model bundles for postop predictions
delta_bundles = {
    "L4S1": L4S1_bundle,
    "LL": LL_bundle,
    "T4PA": T4PA_bundle,
    "L1PA": L1PA_bundle,
    "SS": SS_bundle,
    "GlobalTilt": GT_bundle,
    "SVA": SVA_bundle,
}

Models loaded and verified:
  ✓ Mechanical Failure: mech_fail_logreg
  ✓ L4S1: RidgeRegressor_delta_L4S1
  ✓ LL: RandomForest_delta_LL
  ✓ T4PA: RidgeRegressor_delta_T4PA
  ✓ L1PA: RidgeRegressor_delta_L1PA
  ✓ SVA: XGBRegressor_delta_SVA
  ✓ SS: XGBRegressor_delta_SS
  ✓ Global Tilt: XGBRegressor_delta_GlobalTilt
  ✓ ODI: RidgeRegressor_delta_ODI

In [3]:
# ---- Check categories in training data vs each model ----
train_df = pd.read_csv(config.DATA_PROCESSED)
print("Training data:", config.DATA_PROCESSED)
print(f"  Shape: {train_df.shape}")
print(f"  ASA_CLASS unique: {sorted(train_df['ASA_CLASS'].dropna().unique())}")
print(f"  sex unique: {sorted(train_df['sex'].dropna().unique())}")
print(f"  UIV_implant unique: {sorted(train_df['UIV_implant'].dropna().unique())}")
print(f"  num_levels_cat unique: {sorted(train_df['num_levels_cat'].dropna().unique())}")

Training data: /Users/vanjaglisic/Documents/UW_MSDS/CAPSTONE/repo work/Data-Science-Capstone/data/processed/cleaned_for_modeling.csv
  Shape: (271, 109)
  ASA_CLASS unique: ['1', '2', '3', '4', '4E']
  sex unique: ['FEMALE', 'MALE']
  UIV_implant unique: ['FS', 'Hook', 'PS']
  num_levels_cat unique: ['higher', 'lower']

## Optimization Scenarios

Each scenario uses a different set of composite score weights to explore how the optimizer behaves under different objectives. Predefined presets are in `src/runs.py`. To add a new scenario, add a new entry to `runs.PRESETS` and include its key below.

In [4]:
# =============================================================================
# SELECT SCENARIOS TO RUN
# =============================================================================
# Available presets (defined in src/runs.py):
#   "equal"           - All 6 alignment components weighted equally
#   "mech_fail"       - Primarily mech failure, small alignment weights
#   "mech_fail_t4l1pa"- Mech failure + T4PA-L1PA mismatch
#   "l4s1"            - Primarily L4-S1 in ideal range
#   "t4l1pa"          - Primarily T4PA-L1PA mismatch
#   "equal_plus_mech" - Composite (equal) blended 50/50 with mech failure
#   "odi"             - Primarily lowest predicted postop ODI
#   "gap_score"       - Primarily GAP score + category improvement
#   "gap_score_mech_fail" - GAP score + Mechanical Failure
#   "ll"              - Primarily PI-LL mismatch
#
# To add a new scenario: add an entry to runs.PRESETS in src/runs.py,
# then include its key here.

SCENARIOS = ["equal", "mech_fail", "mech_fail_t4l1pa", "l4s1", "t4l1pa", "gap_score", "gap_score_mech_fail", "ll", "odi"]

# Show selected scenarios
for key in SCENARIOS:
    runs.print_preset(runs.PRESETS[key])

============================================================
  Equal Weights (Composite)
  All 6 alignment components and mechanical failure weighted equally
============================================================
                       GAP Score: 0.1429 ◀
                    L1PA penalty: 0.1429 ◀
                    L4S1 penalty: 0.1429 ◀
                  T4L1PA penalty: 0.1429 ◀
                      LL penalty: 0.1429 ◀
        GAP category improvement: 0.1429 ◀
         Mechanical failure prob: 0.1429 ◀

============================================================
  Minimize Mechanical Failure
  Primarily mechanical failure probability, with small alignment weights
============================================================
                       GAP Score: 0.0500 ◀
                    L1PA penalty: 0.0500 ◀
                    L4S1 penalty: 0.0500 ◀
                  T4L1PA penalty: 0.0500 ◀
                      LL penalty: 0.0500 ◀
        GAP category improvement: 0.0500 ◀
         Mechanical failure prob: 0.7000 ◀

============================================================
  Minimize Mechanical Failure + T4L1PA
  Mechanical failure probability and T4PA-L1PA mismatch weighted equally
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.5000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize L4S1 Penalty
  Primarily L4-S1 in ideal range (35-45°), with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.8000 ◀
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize T4L1PA Penalty
  Primarily T4PA-L1PA mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.8000 ◀
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.5000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.3000 ◀
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize GAP Score and Mechanical Failure
  Primarily overall GAP alignment score and category improvement, with mech failure guard
============================================================
                       GAP Score: 0.4000 ◀
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.1000 ◀
         Mechanical failure prob: 0.5000 ◀

============================================================
  Minimize LL (PI-LL) Penalty
  Primarily PI-LL mismatch, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.8000 ◀
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀

============================================================
  Minimize Postop ODI
  Primarily lowest predicted postoperative ODI, with mech failure guard
============================================================
                       GAP Score: 0.0000
                    L1PA penalty: 0.0000
                    L4S1 penalty: 0.0000
                  T4L1PA penalty: 0.0000
                      LL penalty: 0.0000
        GAP category improvement: 0.0000
         Mechanical failure prob: 0.2000 ◀
                      ODI postop: 0.8000 ◀

In [5]:
UIV_CHOICES, xl, xu = ou.get_decision_config()

print("UIV_CHOICES:", UIV_CHOICES)
print("xl:", xl)
print("xu:", xu)

# Use column names from config
print(pd.DataFrame([xl, xu], index=["xl","xu"], columns=config.DECISION_VAR_NAMES))

UIV_CHOICES: ['Hook', 'PS', 'FS']
xl: [0 0 0 0 0 0 1 2 0]
xu: [2 1 5 1 1 1 6 4 1]
    uiv_code  num_levels_cat_code  num_interbody_fusion_levels  ALIF  XLIF  \
xl         0                    0                            0     0     0
xu         2                    1                            5     1     1

    TLIF  num_rods  num_pelvic_screws  osteotomy
xl     0         1                  2          0
xu     1         6                  4          1

## Test Patient w fixed parameters

In [6]:
# Show holdout patients summary
holdout_df = pd.read_csv(config.DATA_HOLDOUT)

summary_cols = [
    'sex', 'age', 'ASA_CLASS',
    "id", "description", "revision", "mech_fail_last",
    "gap_score_preop", "gap_category", "gap_score_postop", "gap_category_postop",
    "UIV_implant", "num_levels_cat", "num_interbody_fusion_levels",
    "ALIF", "XLIF", "TLIF", "num_rods", "num_pelvic_screws", "osteotomy",
    "ODI_preop"
]
display(holdout_df[summary_cols].set_index("id"))

# Select patient
PATIENT_ID = 6380632
# PATIENT_ID = 2964021  # patient with ODI
patient_fixed = ou.load_patient_data(patient_id=PATIENT_ID, data_path=config.DATA_HOLDOUT)
print(f"\nSelected patient: {PATIENT_ID}")

,sex,age,ASA_CLASS,description,revision,mech_fail_last,gap_score_preop,gap_category,gap_score_postop,gap_category_postop,UIV_implant,num_levels_cat,num_interbody_fusion_levels,ALIF,XLIF,TLIF,num_rods,num_pelvic_screws,osteotomy,ODI_preop
id,,,,,,,,,,,,,,,,,,,,
818588,MALE,78,2.0,mech failure - small GAP improvement;,0,1.0,12.0,SD,10.0,SD,PS,lower,1,0,0,1,3,2,0,NaN
1176294,MALE,71,NaN,mech failure - large GAP improvement;,0,1.0,10.0,SD,1.0,P,FS,lower,1,1,1,0,4,2,1,NaN
2964021,FEMALE,70,3.0,revision - GAP improvement 3 to 1,0,0.0,3.0,MD,1.0,P,PS,lower,2,1,0,0,3,3,0,15.0
6380632,FEMALE,76,3.0,large GAP imporovement,0,0.0,12.0,SD,1.0,P,Hook,higher,2,1,0,0,3,2,0,NaN

Selected patient: 6380632

## Run All Scenarios

For each selected scenario, runs the GA optimizer and collects results. 

**Constraints (all scenarios):** 
- If `num_interbody_fusion_levels > 0`, at least one fusion type (`ALIF`, `XLIF`, or `TLIF`) must be selected.
- If `ALIF=1` and `XLIF=0` and `TLIF=0`, then `num_interbody_fusion_levels` must be < 4.

In [7]:
# Run all selected scenarios
all_results = {}

for key in SCENARIOS:
    preset = runs.PRESETS[key]
    print(f"\n▶ Running: {preset['label']}...")

    result = runs.run_optimization(
        preset=preset,
        patient_fixed=patient_fixed,
        delta_bundles=delta_bundles,
        mech_fail_bundle=mech_fail_bundle,
        xl=xl,
        xu=xu,
        odi_bundle=ODI_bundle,
        pop_size=100,
        n_gen=20,
        seed=42,
        verbose=False,
        top_n=4,
        score_tolerance=2,
    )
    all_results[key] = result
    print(f"  ✓ Best composite: {result['best_result']['composite_score']:.2f}"
          f"  |  Mech fail: {result['best_result']['mech_fail_prob']*100:.1f}%")

print(f"\n{'='*60}")
print(f"Completed {len(all_results)} scenarios.")

▶ Running: Equal Weights (Composite)...
  ✓ Best composite: 4.71  |  Mech fail: 16.5%

▶ Running: Minimize Mechanical Failure...
  ✓ Best composite: 7.33  |  Mech fail: 9.3%

▶ Running: Minimize Mechanical Failure + T4L1PA...
  ✓ Best composite: 1.00  |  Mech fail: 2.0%

▶ Running: Minimize L4S1 Penalty...
  ✓ Best composite: 0.47  |  Mech fail: 2.4%

▶ Running: Minimize T4L1PA Penalty...
  ✓ Best composite: 0.40  |  Mech fail: 2.0%

▶ Running: Minimize GAP Score...
  ✓ Best composite: 10.45  |  Mech fail: 13.8%

▶ Running: Minimize GAP Score and Mechanical Failure...
  ✓ Best composite: 13.05  |  Mech fail: 13.8%

▶ Running: Minimize LL (PI-LL) Penalty...
  ✓ Best composite: 1.79  |  Mech fail: 4.9%

▶ Running: Minimize Postop ODI...
  ✓ Best composite: 0.40  |  Mech fail: 2.0%

============================================================
Completed 9 scenarios.

## Actual surgical plan & outcome for comparison

In [8]:
df_actual = disp.display_actual_outcomes(
    PATIENT_ID, patient_fixed, data_path=config.DATA_HOLDOUT,
    delta_bundles=delta_bundles,
    mech_fail_bundle=mech_fail_bundle,
    odi_bundle=ODI_bundle,
    presets=runs.PRESETS,
)
display(df_actual)

============================================================
ACTUAL SURGICAL PLAN (WHAT WAS PERFORMED)
============================================================
  UIV_implant: Hook
  num_levels_cat: higher
  num_interbody_fusion_levels: 2
  ALIF: 1
  XLIF: 0
  TLIF: 0
  num_rods: 3
  num_pelvic_screws: 2
  osteotomy (PSO): 0

  Mechanical Failure: No
  ODI: N/A (preop) → N/A (12mo)

============================================================
MODEL SCORES FOR ACTUAL PLAN
============================================================
  Mech Failure Prob (predicted): 42.7%

  Scenario Scores (lower is better):
    [equal]                Equal Weights (Composite)                   16.00
    [mech_fail]            Minimize Mechanical Failure                 33.34
    [mech_fail_t4l1pa]     Minimize Mechanical Failure + T4L1PA        21.34
    [l4s1]                 Minimize L4S1 Penalty                        8.54
    [t4l1pa]               Minimize T4L1PA Penalty                      8.54
    [equal_plus_mech]      Equal Alignment + Mechanical Failure        27.12
    [odi]                  Minimize Postop ODI                          8.54
    [gap_score]            Minimize GAP Score                          36.77
    [gap_score_mech_fail]  Minimize GAP Score and Mechanical Failure   39.72
    [ll]                   Minimize LL (PI-LL) Penalty                  9.23

============================================================
ALIGNMENT PARAMETERS: PREOP → POSTOP (ACTUAL)
============================================================

              Parameter    Preop Delta (actual) Postop (actual)
0                    LL     30.4           32.5            62.9
1                    SS     33.8           11.5            45.3
2                  L4S1     34.5            7.0            41.5
3            GlobalTilt     42.2          -23.9            18.3
4                  T4PA     24.8          -15.2             9.6
5                  L1PA     12.2           -4.8             7.4
6                    PI     58.6            2.2            60.8
7                    PT     24.8           -9.3            15.5
8                   SVA    154.6         -124.8            29.8
9                   Age       76              -               -
10            GAP Score     12.0              -             1.0
11         GAP Category       SD              →               P
12  ─── CONSTRAINTS ───
13         PI-LL (0–10)   28.2 ⚠          -30.3          -2.1 ⚠
14   L1PA−ideal (|d|≤3)    3.9 ⚠           -4.8          -0.9 ✓
15         L4S1 (35–45)   34.5 ⚠            7.0          41.5 ✓
16    T4PA−L1PA (|d|≤3)   12.6 ⚠          -10.4           2.2 ✓
17     LL−ideal (|d|≤3)  -28.8 ⚠           32.5           3.7 ⚠
18          GAP Cat (P)     SD ⚠              →             P ✓

## Results per Scenario

In [9]:
from IPython.display import display, Markdown

for key in SCENARIOS:
    r = all_results[key]

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{runs.PRESETS[key]['description']}*"))

    # # Best solution
    # df_comparison = disp.display_optimized_solution(r["best_result"], patient_fixed)
    # display(df_comparison)

    # Top 4 diverse plans
    display(Markdown("**Top diverse plans:**"))
    _ = disp.display_multiple_solutions(r["diverse_df"], patient_fixed)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.6,2.8,1.5,1.6
1,Optimization Score,2.1,2.8,3.2,3.3
2,Mech Fail Prob,5.1%,2.7%,12.9%,13.6%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 2 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,FS
8,num_levels_cat,lower,lower,higher,lower
9,num_interbody_fusion_levels,4,5,4,4
10,ALIF,0,0,0,0
11,XLIF,1,0,1,1
12,TLIF,0,1,0,0
13,num_rods,5,2,4,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.4,51.1,51.0
19,SS,41.7,42.8,41.7,41.3
20,L4S1,40.3,40.8,39.7,38.2
21,GlobalTilt,22.5,24.0,23.1,22.6
22,T4PA,0.3,0.5,0.4,0.5
23,L1PA,1.3,2.6,1.8,0.6
24,SVA,95.2,86.6,95.0,103.8
25,PI,58.6,58.6,58.6,58.6
26,PT,16.9,15.8,16.9,17.3
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.2 ✓,7.5 ✓,7.6 ✓
30,L1PA−ideal (|d|≤3),-7.0 ⚠,-5.7 ⚠,-6.5 ⚠,-7.7 ⚠
31,L4S1 (35–45),40.3 ✓,40.8 ✓,39.7 ✓,38.2 ✓
32,T4PA−L1PA (|d|≤3),-1.0 ✓,-2.1 ✓,-1.4 ✓,-0.1 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-7.8 ⚠,-8.1 ⚠,-8.2 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,2.8,2.8,2.8,2.7
1,Optimization Score,2.7,3.1,3.1,3.6
2,Mech Fail Prob,2.7%,3.2%,3.3%,3.9%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 2 (P),12.0 (SD) → 2 (P),12.0 (SD) → 2 (P),12.0 (SD) → 2 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,5,4,4
10,ALIF,0,0,0,0
11,XLIF,0,0,0,0
12,TLIF,1,1,1,1
13,num_rods,2,1,2,1
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.4,51.4,51.4,51.4
19,SS,42.8,42.8,42.8,42.8
20,L4S1,40.8,39.2,40.6,38.9
21,GlobalTilt,24.0,24.0,23.8,23.8
22,T4PA,0.5,0.8,1.4,1.7
23,L1PA,2.6,3.1,3.1,3.6
24,SVA,86.6,86.6,86.6,86.6
25,PI,58.6,58.6,58.6,58.6
26,PT,15.8,15.8,15.8,15.8
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.2 ✓,7.2 ✓,7.2 ✓,7.2 ✓
30,L1PA−ideal (|d|≤3),-5.7 ⚠,-5.2 ⚠,-5.2 ⚠,-4.7 ⚠
31,L4S1 (35–45),40.8 ✓,39.2 ✓,40.6 ✓,38.9 ✓
32,T4PA−L1PA (|d|≤3),-2.1 ✓,-2.3 ✓,-1.7 ✓,-1.9 ✓
33,LL−ideal (|d|≤3),-7.8 ⚠,-7.8 ⚠,-7.8 ⚠,-7.8 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.5,10.6,10.4,10.5
1,Optimization Score,0.7,1.4,1.7,1.9
2,Mech Fail Prob,1.4%,2.7%,3.3%,3.8%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,4,4
10,ALIF,0,0,0,0
11,XLIF,0,0,1,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,6
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.0,51.1,51.1
19,SS,42.0,41.7,41.8,42.0
20,L4S1,47.4,49.0,46.3,48.3
21,GlobalTilt,22.7,22.7,22.5,22.5
22,T4PA,-0.6,-0.9,1.3,0.1
23,L1PA,0.6,-0.5,1.4,1.1
24,SVA,86.7,82.5,92.6,86.9
25,PI,58.6,58.6,58.6,58.6
26,PT,16.6,16.9,16.8,16.6
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.6 ✓,7.5 ✓,7.5 ✓
30,L1PA−ideal (|d|≤3),-7.7 ⚠,-8.8 ⚠,-6.9 ⚠,-7.2 ⚠
31,L4S1 (35–45),47.4 ⚠,49.0 ⚠,46.3 ⚠,48.3 ⚠
32,T4PA−L1PA (|d|≤3),-1.2 ✓,-0.4 ✓,-0.1 ✓,-1.0 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-8.2 ⚠,-8.1 ⚠,-8.1 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.4,10.5,10.3,10.5
1,Optimization Score,0.3,0.9,1.1,1.2
2,Mech Fail Prob,1.6%,4.0%,5.7%,6.0%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,FS
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,3,5
10,ALIF,0,0,0,0
11,XLIF,0,0,1,0
12,TLIF,1,1,1,1
13,num_rods,5,5,4,5
14,num_pelvic_screws,2,2,2,3
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.0,51.1,51.0
19,SS,41.9,41.6,41.7,41.5
20,L4S1,45.8,47.2,42.7,44.4
21,GlobalTilt,22.7,22.5,23.1,22.6
22,T4PA,-0.3,0.3,2.7,-0.7
23,L1PA,1.1,0.5,2.9,-0.2
24,SVA,89.3,85.2,89.5,98.3
25,PI,58.6,58.6,58.6,58.6
26,PT,16.7,17.0,16.9,17.1
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.6 ✓,7.5 ✓,7.6 ✓
30,L1PA−ideal (|d|≤3),-7.2 ⚠,-7.8 ⚠,-5.4 ⚠,-8.5 ⚠
31,L4S1 (35–45),45.8 ⚠,47.2 ⚠,42.7 ✓,44.4 ✓
32,T4PA−L1PA (|d|≤3),-1.4 ✓,-0.2 ✓,-0.2 ✓,-0.5 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-8.2 ⚠,-8.1 ⚠,-8.2 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.5,10.6,10.4,10.5
1,Optimization Score,0.3,0.6,0.7,0.8
2,Mech Fail Prob,1.4%,2.7%,3.3%,3.8%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,4,4
10,ALIF,0,0,0,0
11,XLIF,0,0,1,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,6
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.0,51.1,51.1
19,SS,42.0,41.7,41.8,42.0
20,L4S1,47.4,49.0,46.3,48.3
21,GlobalTilt,22.7,22.7,22.5,22.5
22,T4PA,-0.6,-0.9,1.3,0.1
23,L1PA,0.6,-0.5,1.4,1.1
24,SVA,86.7,82.5,92.6,86.9
25,PI,58.6,58.6,58.6,58.6
26,PT,16.6,16.9,16.8,16.6
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.6 ✓,7.5 ✓,7.5 ✓
30,L1PA−ideal (|d|≤3),-7.7 ⚠,-8.8 ⚠,-6.9 ⚠,-7.2 ⚠
31,L4S1 (35–45),47.4 ⚠,49.0 ⚠,46.3 ⚠,48.3 ⚠
32,T4PA−L1PA (|d|≤3),-1.2 ✓,-0.4 ✓,-0.1 ✓,-1.0 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-8.2 ⚠,-8.1 ⚠,-8.1 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.6,1.6,1.5,1.5
1,Optimization Score,4.7,4.9,5.0,5.3
2,Mech Fail Prob,4.1%,5.1%,6.0%,7.3%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,4,3
10,ALIF,0,0,0,0
11,XLIF,1,1,1,1
12,TLIF,0,0,0,0
13,num_rods,5,5,4,4
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.1,51.1,51.1
19,SS,41.7,41.7,41.7,41.7
20,L4S1,40.5,40.3,38.6,38.4
21,GlobalTilt,22.7,22.5,23.1,23.1
22,T4PA,-0.6,0.3,0.6,1.5
23,L1PA,0.8,1.3,1.8,2.3
24,SVA,95.2,95.2,94.8,89.5
25,PI,58.6,58.6,58.6,58.6
26,PT,16.9,16.9,16.9,16.9
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.5 ✓,7.5 ✓,7.5 ✓
30,L1PA−ideal (|d|≤3),-7.5 ⚠,-7.0 ⚠,-6.5 ⚠,-6.0 ⚠
31,L4S1 (35–45),40.5 ✓,40.3 ✓,38.6 ✓,38.4 ✓
32,T4PA−L1PA (|d|≤3),-1.4 ✓,-1.0 ✓,-1.2 ✓,-0.8 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-8.1 ⚠,-8.1 ⚠,-8.1 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,1.6,1.6,1.5,1.5
1,Optimization Score,5.2,5.6,6.1,6.2
2,Mech Fail Prob,4.1%,5.1%,6.0%,6.2%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P),12.0 (SD) → 1 (P)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,Hook,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,4,4,3
10,ALIF,0,0,0,0
11,XLIF,1,1,1,1
12,TLIF,0,0,0,0
13,num_rods,5,5,4,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.1,51.1,51.1
19,SS,41.7,41.7,41.7,41.7
20,L4S1,40.5,40.3,38.6,40.0
21,GlobalTilt,22.7,22.5,23.1,22.5
22,T4PA,-0.6,0.3,0.6,1.2
23,L1PA,0.8,1.3,1.8,1.8
24,SVA,95.2,95.2,94.8,90.0
25,PI,58.6,58.6,58.6,58.6
26,PT,16.9,16.9,16.9,16.9
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.5 ✓,7.5 ✓,7.5 ✓
30,L1PA−ideal (|d|≤3),-7.5 ⚠,-7.0 ⚠,-6.5 ⚠,-6.5 ⚠
31,L4S1 (35–45),40.5 ✓,40.3 ✓,38.6 ✓,40.0 ✓
32,T4PA−L1PA (|d|≤3),-1.4 ✓,-1.0 ✓,-1.2 ✓,-0.6 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-8.1 ⚠,-8.1 ⚠,-8.1 ⚠
34,GAP Category (P),P ✓,P ✓,P ✓,P ✓

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.5,10.5,11.2,10.4
1,Optimization Score,1.1,1.5,1.6,1.6
2,Mech Fail Prob,1.4%,3.2%,4.3%,3.9%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,lower
9,num_interbody_fusion_levels,5,5,4,4
10,ALIF,0,0,1,0
11,XLIF,0,0,0,1
12,TLIF,1,1,1,1
13,num_rods,6,5,5,5
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.0,51.6,51.1
19,SS,42.0,41.6,42.3,41.7
20,L4S1,47.4,47.4,55.0,44.6
21,GlobalTilt,22.7,22.7,22.5,22.5
22,T4PA,-0.6,-0.6,-0.6,1.5
23,L1PA,0.6,0.0,-0.5,1.9
24,SVA,86.7,85.2,89.6,95.2
25,PI,58.6,58.6,58.6,58.6
26,PT,16.6,17.0,16.3,16.9
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.6 ✓,7.0 ✓,7.5 ✓
30,L1PA−ideal (|d|≤3),-7.7 ⚠,-8.3 ⚠,-8.8 ⚠,-6.4 ⚠
31,L4S1 (35–45),47.4 ⚠,47.4 ⚠,55.0 ⚠,44.6 ✓
32,T4PA−L1PA (|d|≤3),-1.2 ✓,-0.6 ✓,-0.1 ✓,-0.4 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-8.2 ⚠,-7.6 ⚠,-8.1 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*

**Top diverse plans:**

============================================================
SOLUTIONS COMPARISON
============================================================

,Parameter,Sol 1,Sol 2,Sol 3,Sol 4
0,Alignment Score,10.5,10.6,10.4,10.5
1,Optimization Score,0.3,0.6,0.7,0.8
2,Mech Fail Prob,1.4%,2.7%,3.3%,3.8%
3,Predicted ODI,N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI),N/A (no preop ODI)
4,GAP Score,12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD),12.0 (SD) → 4 (MD)
5,────────────,──────────,──────────,──────────,──────────
6,SURGICAL PLAN,,,,
7,UIV_implant,Hook,PS,Hook,Hook
8,num_levels_cat,lower,lower,lower,higher
9,num_interbody_fusion_levels,5,5,4,4
10,ALIF,0,0,0,0
11,XLIF,0,0,1,0
12,TLIF,1,1,1,1
13,num_rods,6,6,6,6
14,num_pelvic_screws,2,2,2,2
15,osteotomy (PSO),1,1,1,1
16,────────────,──────────,──────────,──────────,──────────
17,POSTOP VALUES,,,,
18,LL,51.1,51.0,51.1,51.1
19,SS,42.0,41.7,41.8,42.0
20,L4S1,47.4,49.0,46.3,48.3
21,GlobalTilt,22.7,22.7,22.5,22.5
22,T4PA,-0.6,-0.9,1.3,0.1
23,L1PA,0.6,-0.5,1.4,1.1
24,SVA,86.7,82.5,92.6,86.9
25,PI,58.6,58.6,58.6,58.6
26,PT,16.6,16.9,16.8,16.6
27,────────────,──────────,──────────,──────────,──────────
28,CONSTRAINTS,,,,
29,PI-LL (0–10),7.5 ✓,7.6 ✓,7.5 ✓,7.5 ✓
30,L1PA−ideal (|d|≤3),-7.7 ⚠,-8.8 ⚠,-6.9 ⚠,-7.2 ⚠
31,L4S1 (35–45),47.4 ⚠,49.0 ⚠,46.3 ⚠,48.3 ⚠
32,T4PA−L1PA (|d|≤3),-1.2 ✓,-0.4 ✓,-0.1 ✓,-1.0 ✓
33,LL−ideal (|d|≤3),-8.1 ⚠,-8.2 ⚠,-8.1 ⚠,-8.1 ⚠
34,GAP Category (P),MD ⚠,MD ⚠,MD ⚠,MD ⚠

## Actual vs. Optimized Plans per Scenario

For each scenario, the **Actual** column (highlighted) shows the real surgical plan scored with that scenario's weights. The remaining columns show the optimizer's top diverse recommendations.

In [10]:
# Build x vector for the actual surgical plan (from holdout data)
holdout_row = holdout_df[holdout_df["id"] == PATIENT_ID].iloc[0]
actual_x = []
for var_spec in config.DECISION_VAR_SPECS:
    col = var_spec["col_name"]
    val = holdout_row[col]
    if var_spec.get("categorical", False):
        actual_x.append(var_spec["choices"].index(val))
    else:
        actual_x.append(int(val))
actual_x = np.array(actual_x)

# Display each scenario: actual plan (highlighted) + top diverse optimized plans
for key in SCENARIOS:
    r = all_results[key]
    preset = runs.PRESETS[key]
    weights = preset["weights"]

    # Evaluate the actual plan with this scenario's weights
    actual_eval = ou.evaluate_solution(
        actual_x, patient_fixed, delta_bundles, mech_fail_bundle,
        weights=weights, odi_bundle=ODI_bundle
    )

    display(Markdown(f"### {r['label']}"))
    display(Markdown(f"*{preset['description']}*"))
    disp.display_solutions_with_actual(r["diverse_df"], patient_fixed, actual_eval)

### Equal Weights (Composite)

*All 6 alignment components and mechanical failure weighted equally*

### Minimize Mechanical Failure

*Primarily mechanical failure probability, with small alignment weights*

### Minimize Mechanical Failure + T4L1PA

*Mechanical failure probability and T4PA-L1PA mismatch weighted equally*

### Minimize L4S1 Penalty

*Primarily L4-S1 in ideal range (35-45°), with mech failure guard*

### Minimize T4L1PA Penalty

*Primarily T4PA-L1PA mismatch, with mech failure guard*

### Minimize GAP Score

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize GAP Score and Mechanical Failure

*Primarily overall GAP alignment score and category improvement, with mech failure guard*

### Minimize LL (PI-LL) Penalty

*Primarily PI-LL mismatch, with mech failure guard*

### Minimize Postop ODI

*Primarily lowest predicted postoperative ODI, with mech failure guard*